### ISSUE TITLE
Using Schemas property to refernece and include schemas results in duplicate classes in ASP.NET Web API

### ISSUE THREAD

**Issue by WadeBarnes** [mulesoft-labs/raml-dotnet-tools#1]
From the following RAML four classes end up being created:
* Lognote - based on the the schema key reference (lognote).
* LogNoteKeyGetOKResponseContent - based on the /lognotes/{logNoteKey} - Get reference to the schemas key (lognote)
* Lognotes - based on the schema key reference (lognotes).
* LognotesGetOKResponseContent - based on the /lognotes - Get reference to the schemas key (lognotes)

The samples use the *OKResponseContent class name for inline schema references.  Where in this cases I would think the schemas key reference is more appropriate choice for the name.

The controller implementation then uses a mixture of the generated classes.  Where is would normally be using a single set.

Controller Implementation:
<pre>
    [RoutePrefix("lognotes")]
    public partial class LognotesController : ApiController
    {

        /// <summary>
		/// Get a list of available lognotes.
		/// </summary>
		/// <returns>Lognotes[]</returns>
        [ResponseType(typeof(Lognotes[]))]
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase()
        {
            // Do not modify this code
            return ((ILognotesController)this).Get();
        }

        /// <summary>
		/// Get the specific lognote. 
		/// </summary>
		/// <param name="logNoteKey"></param>
		/// <returns>LogNoteKeyGetOKResponseContent</returns>
        [ResponseType(typeof(LogNoteKeyGetOKResponseContent))]
        [HttpGet]
        [Route("{logNoteKey}")]
        public virtual IHttpActionResult GetByLogNoteKeyBase([FromUri] string logNoteKey)
        {
            // Do not modify this code
            return ((ILognotesController)this).GetByLogNoteKey(logNoteKey);
        }
    }
</pre>

Source RAML:
<pre>
#%RAML 0.8
---
title: DARS
version: 0.0.1
protocols: [HTTPS]
baseUri: https://test
mediaType: application/json
securedBy: [basic]

securitySchemes:
  - basic:
      type: Basic Authentication

schemas:
 - lognote: !include ./samples/include-lognote.schema
 - lognotes: !include ./samples/include-lognotes.schema

resourceTypes:
  - readOnlyCollection:
      get:
        description: Get a list of available <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!pluralize>>
          404:
            body:
              application/json:
                example: |
                  {"message": "No items matching the given criteria were found."}

  - readOnlyCollectionItem:
      get:
        description: |
          Get the specific <<resourcePathName|!singularize>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
          404:
            body:
              application/json:
                example: |
                  {"message": "File could not be found."}

/lognotes:
  type:
    readOnlyCollection:
  /{logNoteKey}:
    type:
      readOnlyCollectionItem:
</pre>

**Comment by woodp** [comment]
fix will be included in next release

**Comment by woodp** [comment]
fixed in v 1.0.0
