### ISSUE TITLE
Commandline tools

### ISSUE THREAD

**Issue by skjohansen** [mulesoft-labs/raml-dotnet-tools#10]
Are there any commandline tools which does the same as the Visual Studio plugin?
What thinking is something like:
raml-generator http:///myraml.location
raml-update

**Comment by robertbird** [comment]
yes please! +1

**Comment by woodp** [comment]
Hi @skjohansen and @robertbird  

We are working on this feature, we would like to get feedback on how you would use these tools. 
- As part of a CI / automation process ? 
- Generation and then use with Visual Studio Code or any other editor different than Visual Studio ?
- Other ?

Feedback on this will help us provide a better tool. Thank you.

**Comment by skjohansen** [comment]
Hi,
My first thought was to use it in combination with Visual Studio Code, and secondly to use it in CI and other scripting.
Nice PowerShell support would be a plus :+1: :)

**Comment by johlrich** [comment]
For me it's mostly about having it available for use outside of Visual Studio. 

In particular I'd like to be able to setup a simple build process around the workflow I've been experimenting with using the API Workbench plugin for Atom.

**Comment by woodp** [comment]
First version of Command Line Tool available [here](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/command-line/RAMLGen.zip)
