### ISSUE TITLE
AVG detects xmllint js library as a virus

### ISSUE THREAD

**Issue by a2dude** [mulesoft-labs/raml-dotnet-tools#101]
I installed from vs gallery, created an asp.net 5 webapi project and attempted to upload a pre-existing raml 0.8 definition.

This generated an exception in raml-1-0-parser reported in the dialog textbox and an alert from my av that the script contained a virus.  The offending file has been deleted and I now get an exception stating the parser file is not found.

I went to npmjs and could not find raml-1-0-parser which seems curious.

Of course this could have been a pre-existing issue but my belief is that the offending file(s) arrived on my machine as a result of installing your product.  Are you aware of any issues and can you offer any guidance?

**Comment by a2dude** [comment]
Cleaned machine and reinstalled.  This virus issue was reproduced:

C:\Users\andy\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\bztayrjk.qkc\node_modules\raml-1-0-parser\node_modules\xmllint-hack2\xmllint.js;"Virus found XPL/Gen.K.90_30";"Unresolved";"Unresolved";"High"

**Comment by a2dude** [comment]
Cloning your repo and running a virus scan on the downloaded content without taking further action yields the following to instances of infected xmllint.js:

- .\Raml.Tools.Tests\node_modules\raml-1-0-parser\node_modules\xmllint-hack2

- .\MuleSoft.RAML.Tools\node_modules\raml-1-0-parser\node_modules\xmllint-hack2

**Comment by woodp** [comment]
We rely on a RAML js parser, which is here: https://github.com/raml-org/raml-js-parser-2/
This issue has already been added: https://github.com/mulesoft/api-workbench/issues/189
There it says it's a false alarm. 
Will be watching that issue to apply any workarounds here too.

**Comment by a2dude** [comment]
I am astonished that this has not been resolved when first raised.  How can anyone sensibly proceed and use this code on the basis of such a vague assurance! 

Surely anyone ignoring such an error should be fired on the spot.  Doesn't this create a significant issue for anyone who wants to use your code?

**Comment by woodp** [comment]
AVG detected the virus on xmllint library https://github.com/kripken/xml.js/issues/17
It was reported to AVG.

**Comment by woodp** [comment]
latest update of AVG no longer detects xmllint as a virus
