### ISSUE TITLE
Resource type query parameters not applied

### ISSUE THREAD

**Issue by marpit** [mulesoft-labs/raml-dotnet-tools#102]
If I have RAML definition with resource type and uri parameters, generated controller doesn't have right signature. Parameters from resource type missing.

**Comment by woodp** [comment]
Hi @marpit, could you please provide a sample where this is reproducible ?

**Comment by marpit** [comment]
So, We have resource type

`resourceTypes:
  - dataPoints:
      description: Time series of data points.
      get:
        description: Gets time series of data points.
        queryParameters:
          pageSize:
            description: Use this parameter to specify the page size for the results. Maximum available page size for this API is 20000.
            type: integer
            example: 1000
            required: false
            default: 10000
          pagingState:
            description: Use this parameter to specify the next page rather than the initial page of results. For the initial request/call, this parameter can be omitted or null can be passed. For subsequent requests/calls, the paging state in the response from the previous call should be passed.
            type: string
            required: false
            default: null
          start:
            description: Use this parameter to specify the start of the interval you want to get data for. When both start and end is used, start must preceed end. End cannot be used without start. When only start is used, end is set to current date and time. When both start and end is omitted end is set to current date and time and start is set to current date and time minus 7 days.
            example: 2016-01-01T14:00:00.0000000+01:00
            required: false
          end:
            description: Use this parameter to specify the end of the interval you want to get data for. When both start and end is used, start must preceed end. End cannot be used without start. When only start is used, end is set to current date and time. When both start and end is omitted end is set to current date and time and start is set to current date and time minus 7 days.
            example: 2016-01-11T12:00:00.0000000+01:00
            required: false
`
And there is used

`/deviceDataPoints/{macId}/{deviceId}/{variableId}:
  type: dataPoints
  uriParameters:
    macId: 
      description: Unique identifier of the gateway.
      type: string
      required: true
    deviceId: 
      description: Unique identifier of the device connected to the gateway.
      type: string
      required: true
    variableId:
      description: Unique identifier of the variable.
      type: string
      required: true`

 If I use RAML tool at version 1.4, Controler's signature is good (signature contains parameters from type and from query parameters). When I upgrade to version 2.0.3, signature have query parameters only.

**Comment by woodp** [comment]
Just to be sure we are on the same page here. I do get Uri parameters generated on the controller. What I do **not** get is **query** parameters.
