### ISSUE TITLE
Add support for DateTimeOffset

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#103]
Hi,

In our responses we need to be able to send back a datetime + offset from UTC, and this is supported in C# by using DateTimeOffset

As per Raml 1.0 specs the types "date-only, time-only, datetime-only" doesn't support time zone offset, while the type "datetime" supports rfc3339

Based on that can raml tools be adjusted to generate 
DateTime when type is "date-only, time-only or datetime-only" 
DateTimeOffset when type is "datetime"

Thanks

**Comment by woodp** [comment]
Hi @amikhaildev, will consider your request.

**Comment by woodp** [comment]
RAML 1 example to obtain a DateTimeOffset type in the generated code:

    types:
        datetimeoffsetprop:
            type: date
            format: rfc2616
