### ISSUE TITLE
Code isn't generated properly if properties of schema are subset properties of other schema

### ISSUE THREAD

**Issue by marpit** [mulesoft-labs/raml-dotnet-tools#108]
If first schema contains some properties and second schema contains the same properties (same type and name) and add others, tool generate only one class, which have properties from first schema only. Class for second schema isn't generated, bat in response is used class, which is generated for first schema.

**Comment by woodp** [comment]
Thanks @marpit for the feedback. 
Can't seem to reproduce this. Could you please provide a sample ?
