### ISSUE TITLE
Unable to install latest release on VS2015

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#109]
Hi,

I'm using raml dotnet tools with VS2015, I didn't have any issues in installing it for previous release
For the latest release 2.0.4 I can't install it to VS2015, I tried both installing with vsix file, and from inside visual studio (search can't find it at all)

Please advise how can I install the latest release on VS2015

Regards,
Amgad

**Comment by woodp** [comment]
Fixed in new release (v 2.0.5)
