### ISSUE TITLE
json object naming limitation

### ISSUE THREAD

**Issue by olssochk** [mulesoft-labs/raml-dotnet-tools#11]
I came across a problem with JSON and RAML and the generated C# classes. It seems like the name of the JSON objects must be unique within the whole RAML file.

The easiest way to describe my problem is with this simple RAML file:
![capture](https://cloud.githubusercontent.com/assets/13046720/8358298/c4395dc0-1b5f-11e5-8063-5e821b9f3a66.PNG)

The problem here is that we have a JSON object with the same name in both schemas named 'informationPart'. Even though the definition of the objects are different in 'somethings' and 'somethingsMore' there will be just one generated C# class named 'InformationPart.cs':

    public partial class InformationPart
    {
        [JsonProperty("something1")]
        public string Something1 { get; set; }
        [JsonProperty("something2")]
        public string Something2 { get; set; }
    } // end class

and this class will be used by both the generated classes 'SomethingsPostRequestContents.cs' and 'SomethingsMorePostRequestContents.cs' even though it is only feasible for the first one.

As see this as a bug in the tool.

**Comment by woodp** [comment]
fixed in last release
