### ISSUE TITLE
String array properties not generated

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#111]
Hi,

In some of the requests we need to include string array (e.g. ["string1", "string2", "string3"])
I tried to define this in raml in both ways
>      Messages?: string[]

       Messages?:
        type: array
        items:
          type: string

Both ways doesn't generate the property 'Messages' at all, please advise how can we achieve this

Thanks

**Comment by woodp** [comment]
I think the problem you are having is with the optional mark "?". It can only be used in properties not in a root type. Please try removing the question mark.

**Comment by eiki25** [comment]
All kind of array properties seems to be skipped when using RAML 1.0,  arrays only works for RAML 0.8 schemas. Any news on fix?
