### ISSUE TITLE
Generate API Client Code from a RAML Definition in .NET core projects

### ISSUE THREAD

**Issue by spallister** [mulesoft-labs/raml-dotnet-tools#115]
Upon installing the RAML Tools for .NET v2.05 VSIX extension for Visual Studio (VS) 2015 Community Edition, I only have the option to 'Add RAML Contract...' from the project node, whereas the option to 'Add RAML Reference...' from the References node is greyed out (disabled).  Note that I am able to successfully generate client code from the 'Add RAML Reference...' option when using the VSIX extension in VS 2013 Professional Edition.

Is the ability to generate API client code from RAML definitions, really only supported in VS 2013, or have I missed something in the documentation that explains how this is possible in VS 2015?

Thanks for your help, and this tool!

**Comment by woodp** [comment]
'Add RAML Reference...' is available in Visual Studio 2015 but not for .net core projects (since the code produced is not .net core compatible).

**Comment by spallister** [comment]
As a workaround for anyone that is trying to use this solution with a .NET Core project, the following might work for you (it did for me):

Run the code generator in a full .NET framework project, then import the generated 'API References' folder into your .NET Core project.  From there, include the following dependencies, and setup your frameworks > imports to allow in the Microsoft.AspNet.WebApi.Client dependency (which satisfies the System.Net.Http.Formatting dependency in the generated client code):

```
{
  ...
  "dependencies": {
    ...
    "RAML.Api.Core": "0.9.10",
    "System.Net.Http": "4.3.0",
    "System.Xml.XmlSerializer": "4.3.0",
    "System.Runtime.Serialization.Xml": "4.3.0",
    "Microsoft.AspNet.WebApi.Client": "5.2.3",
    ...
  },
  ...
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  ...
}
```

Also note that I'm on .NET Core 1.1.

**Comment by woodp** [comment]
That's interesting, thanks for the feedback

**Comment by woodp** [comment]
The trick is to add "portable-net45+win8" to the imports. That allows "Microsoft.AspNet.WebApi.Client" package to be used in a .net core app.
More info [here](https://github.com/aspnet/Home/issues/1558)

Thanks again @spallister 
Will check what you mention about SchemaValidation

**Comment by woodp** [comment]
SchemaValidation tests worked fine

**Comment by KusumSitecore** [comment]
@woodp  - Hi Do we have RAML Support for Generate RAML from ASPNET CORE WEB API.
