### ISSUE TITLE
WebApiConfig access denied on "Enable RAML metadata output"

### ISSUE THREAD

**Issue by luisxkimo** [mulesoft-labs/raml-dotnet-tools#117]
Hi everyone,

When I try to enable metadata output, for generate RAML specification with an implemented Web API, appears a message saying that WebApiConfig.cs is denied.

![ramlerror](https://cloud.githubusercontent.com/assets/6990299/21616946/01e5d9b4-d1e4-11e6-8771-1719020f1082.png)

I don't know what is the reason for this behavior, but if I continue with the installation, the installation process enter in a infinite bucle.

![infinitebucle](https://cloud.githubusercontent.com/assets/6990299/21616947/01e78b6a-d1e4-11e6-8eb7-8d3fd1190a58.png)

But, if I cancel the process, in the context menu appears the option "Disable RAML metadata output", but nothing was created (controllers, etc.) related with RAML.

.NET Framework: 4.6.2
Visual Studio 2015 Update 3
Microsoft AspNet WebApi 5.2.3

**Comment by woodp** [comment]
Hi @luisxkimo 
Have you checked if the path on the error message is correct ? Is the WebApiConfig.cs file really in that path ?
Have you changed the permissions on that file ?

**Comment by luisxkimo** [comment]
Hi @woodp ,

Yes the file path it's correct, and with de VS in admin mode the problem persists. The file doesn't have special permissions.

Regards.

**Comment by woodp** [comment]
Hi @luisxkimo, please let me know if that worked.

Also, here is a more in-depth documentation for RAML metadata:
https://github.com/mulesoft-labs/raml-dotnet-apiexplorer/tree/develop
Following it you could add the functionality manually.

**Comment by luisxkimo** [comment]
Hi @woodp ,

I've reviewed the permissions of the local file and are correct. I'm using P4 and when I checking the file, my user have all permissions over it.

I will try with the manual way, but for me the plugin continue not working... :(

You can close the issue or maintain on hold for news.

Regards and thanks so much for the help
