### ISSUE TITLE
Error importing valid Mulesoft Anypoint api.raml spec

### ISSUE THREAD

**Issue by sicollins** [mulesoft-labs/raml-dotnet-tools#118]
Keep getting following error when trying to import raml spec created in Mulesoft Anypoint into VS 2015 Community.

Error while parsing raml file unable to cast object of type 'System.Object[]' to type 'System.Collections.Generic.IDictionary`2[system.String.Object]'.

Have tried this in both standard .NET and Core WebApi projects, same error.
RAML VS Tools version 2.0.5
Have validated the raml file in various online tools and no problems highlighted, nor in anypoint api designer.

Is there somewhere I can get a more detailed error of exactly where this is failing. VS just hangs afterwards?

**Comment by sicollins** [comment]
Have also tried importing this very basic raml example:

https://raw.githubusercontent.com/raml-org/raml-examples/master/helloworld/helloworld.raml

It gets further and creates the Contracts folder but also throw an error and no controller is created.

![vs_raml_error](https://cloud.githubusercontent.com/assets/5272608/21806196/e31be702-d72f-11e6-9f3e-7627e0b0c247.jpg)

**Comment by woodp** [comment]
For the first error I need the RAML to be able to reproduce the error.

For the second one (helloworld.raml) please use "Controllers" and "Models" for the folders (remove the slash "/"). Anyway I see this as a bug, so I will add a separate issue.

Also you are defining a inlined json schema using the "**type**" keyword, you should use "**schema**" or leave type but specify it as a [RAML 1 type.](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#raml-data-types)

Change keyword for "schema":
```
...
          schema: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
...
```

Or using RAML 1 type:

```
...
            type:
                properties:
                    message:
...
```

**Comment by woodp** [comment]
https://github.com/mulesoft-labs/raml-dotnet-tools/issues/119

**Comment by sicollins** [comment]
Changed the hellowworld.raml, type to schema as you suggested and also tried changing it to RAML 0,8 declaration but neither work.

Error: Object reference not set to an instance of an object.

I can't supply the actual RAML file I'm building as it's from a private client repo and is massive with lots of includes.

I've tried importing a few other raml api examples fromhere https://github.com/raml-apis into a .NET Core WebApi, e.g. the Stormpath RAML 0.8 spec which worked but others didn't.

I could only find one RAML 1.0 example here: https://github.com/raml-apis/AdhereTech
But this also errors when importing.

It would be good if the error messaging has more detail like filename and line number.

Do you have any complex RAML 1.0 examples I could try?

**Comment by woodp** [comment]
As I explained above the "Error: Object reference not set to an instance of an object." is because of the path of the folders. Use "Controllers" and "Models" for the folders (remove the slash "/")

**Comment by woodp** [comment]
Examples of RAML can be found [here](https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/Raml.Tools.Tests/files)

For example: https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/Raml.Tools.Tests/files/raml1/salesOrders.raml

**Comment by sicollins** [comment]
The error: "Error: Object reference not set to an instance of an object."

Happens with the slashes removed.

![vs_raml_error2](https://cloud.githubusercontent.com/assets/5272608/21844136/6d8c9dd6-d7e5-11e6-8485-a17550c8e32d.jpg)

And the file I'm using to import is very simple:
#%RAML 0.8
title: Hello world # required title

/helloworld: # optional resource
  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            schema: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: | # example how a response looks like
              {
                "message": "Hello world"
              }

I've also tried the RAML 1.0 chinook-v1.raml and that fails with same error.

However, salesOrders.raml you suggested does import.

So there is clearly something wrong with the import parsing. Without more detailed error messaging with line number/file where the failure occurred it's hard to say or debug.

I'm using RAML VS Tools v2.0.5 in VS 2015 Update 3 in a .NET Core v1.0.1 WebAPI.

Any help on this much appreciated.

**Comment by woodp** [comment]
Sorry, but I cannot reproduce the errors.

Testing helloword (changed type by schema) with VS Community 2005 Update 3, Asp.Net Core with WebApi template.
Preview:

![preview](https://cloud.githubusercontent.com/assets/675793/21892500/ea0f1246-d8b5-11e6-8dc6-51eeb3082499.png)

Code generated successfully:

![generated-code](https://cloud.githubusercontent.com/assets/675793/21892529/0cb3753a-d8b6-11e6-9d5c-ec3bc06c0b67.png)

Chinook-v1.raml also works fine.

Please try with logging on and send me the log. See https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/

Also if you can try reinstalling the extension and/or in a different machine.

**Comment by woodp** [comment]
This is what you get when RAML has parsing errors:

![error-reporting](https://cloud.githubusercontent.com/assets/675793/21892899/a568b4c4-d8b7-11e6-8dc1-d1224d1c4cd4.png)

**Comment by woodp** [comment]
Also, I tested AdhereTech and it actually does not import correctly, although it is not a null reference error what I get.

I added a [separate issue](https://github.com/mulesoft-labs/raml-dotnet-tools/issues/121) for it.

**Comment by richardcase** [comment]
I am also getting the 'Object reference not set to an instance of an object' error with a RAML 1.0 specification downloaded from Anypoint.

Anypoint is reporting no issues. The tooling seems to be really flaky.
