### ISSUE TITLE
All included JSON schema files must have unique file names even though they reside in different directories

### ISSUE THREAD

**Issue by olssochk** [mulesoft-labs/raml-dotnet-tools#12]
It is possible to include JSON schema files, in the RAML file, with the same name as long as they reside in different catalogs. But when you add the RAML contract file in Visual Studio (2013 in my case) the schema files are copied in to one single directory, in to the VS project 'Contracts/includes' directory. So if there already exist a file with same name it will be overwritten. The easiest way to explain my problem is with a simple RAML file example:

![capture](https://cloud.githubusercontent.com/assets/13046720/8357857/60d64bdc-1b5d-11e5-8bd9-50e514ad412b.PNG)

When you add this RAML contract in to VS there will be just one schema file copied (which one I don't know), 'Contracts/includes/post-body-schema.json'. I would expect that there should be two sub directories under 'includes' called 'somethings' and 'somethingsMore' with its own version of the schema file.

I do consider this as a bug in the tool even though it is not a super major one. You could of course quite easily work around the problem by making sure to have unique schema file names.

**Comment by olssochk** [comment]
Crappy formatting here it the RAML file is in an image:
![capture](https://cloud.githubusercontent.com/assets/13046720/8356062/3433f49e-1b53-11e5-91e4-1a640aefeb3c.PNG)

**Comment by olssochk** [comment]
Seems like I have a hard time to get this right. Here is another image with correct syntax (without the little red cross):
![capture](https://cloud.githubusercontent.com/assets/13046720/8356519/2ab936ba-1b56-11e5-99a5-3d3cf239153a.PNG)

**Comment by dmalanij** [comment]
Regarding this and #16 and #19, it would be really good to get the different relative folders names preserved when the "include" default folder is created. That would prevent this issue as well as support more comprehensive file structure.

**Comment by woodp** [comment]
fixed in last release
