### ISSUE TITLE
Incorrect detection of "uses:" clause

### ISSUE THREAD

**Issue by woodp** [mulesoft-labs/raml-dotnet-tools#121]
Incorrect detection of "uses:" clause with keywords ending on "uses:"

**Comment by tb-wwparker** [comment]
I'm unclear about this issue. From more work, I have found that #126 is caused by specific data in the RAML files (which doesn't have a uses clause). Do your later comments mean that this is an actual bug in 2.0.5 and will be fixed in a future version?

**Comment by woodp** [comment]
@tb-wwparker it happens when any keyword contains "uses" (e.g. "pauses"). It incorrectly detects it as a uses clause. If that's not your case then please provide a RAML sample.
