### ISSUE TITLE
Command Line Returns "Length cannot be less than zero"

### ISSUE THREAD

**Issue by yesitspeter** [mulesoft-labs/raml-dotnet-tools#124]
Upon running the command line generator for both client and server, each responds with a cryptic error message "Error: Length cannot be less than zero.  Parameter name: length"
[hello_api.zip](https://github.com/mulesoft-labs/raml-dotnet-tools/files/726919/hello_api.zip)

**Comment by woodp** [comment]
I don't get that error. I get the same errors that I got with the sample uploaded for your other issue...(125)
