### ISSUE TITLE
Inheriting from Unknown Type

### ISSUE THREAD

**Issue by yesitspeter** [mulesoft-labs/raml-dotnet-tools#125]
When loading a simple API with resource types into the .Net RAML tools, I receive a message "Inheriting from Unknown Type" several times in the dialog.
 
- None of the other tools (API Console, RAML2HTML) report this issue.  I can't seem to find a problem with the RAML files.  

- The message is cryptic: there are no line numbers, or further details that should be available within the context that's generating that error message.  

I am using Version 2.0.5

![capture](https://cloud.githubusercontent.com/assets/13875703/22251305/45e3144e-e218-11e6-9b2b-f59054430e3f.PNG)
[hello_api.zip](https://github.com/mulesoft-labs/raml-dotnet-tools/files/726931/hello_api.zip)

**Comment by woodp** [comment]
The tool is based on the raml parser, this is the exact messages I get from the js parser (using the version that the tool uses currently).
I also get the line numbers from the js parser, for some reason it is failing to informing that.
I will add the absence of the line error as a separate issue.
Also I will check if updating the js parser I get different results.

**Comment by woodp** [comment]
After updating to the latest js parser the RAML parsing errors disappear.
Will update it for next release:  #130
