### ISSUE TITLE
get namespace error on RAML.WebApiExplorer.DocumentationProviderConfig.IncludeXmlComments();

### ISSUE THREAD

**Issue by sonicdivx** [mulesoft-labs/raml-dotnet-tools#127]
Doing a build (to include XMLComments) I get a missing assembly reference error on 

RAML.WebApiExplorer.DocumentationProviderConfig.IncludeXmlComments();

I looked at Object Browser and "DocumentationProviderConfig" does not exist.

Thanks

**Comment by timcromarty** [comment]
I have the same issue. In a .Net Core project, how do I configure the inclusion of XML comments?

**Comment by woodp** [comment]
DocumentationProviderConfig is for asp.net web api projects only, it does not work on .net core projects
