### ISSUE TITLE
DotNet RAML parser cannot handle nested JSON schemas

### ISSUE THREAD

**Issue by olssochk** [mulesoft-labs/raml-dotnet-tools#13]
The tool can't generate the expected C# classes for this example RAML file:

![a1](https://cloud.githubusercontent.com/assets/13046720/8379359/c510060c-1c1f-11e5-84fc-4075c358e897.PNG)
![a2](https://cloud.githubusercontent.com/assets/13046720/8379363/c87364a6-1c1f-11e5-95d8-c68f52032b0b.PNG)

only the following classes will be generated:

![refgenfiles](https://cloud.githubusercontent.com/assets/13046720/8378858/8d811b02-1c1c-11e5-9a8d-ca66f8cb4849.PNG)

But if we include the fully expanded JSON schema in the body section of the "authors" put method like this:

![incauth](https://cloud.githubusercontent.com/assets/13046720/8378900/c1d9d218-1c1c-11e5-8b67-64ed8e41dda3.PNG)

The expected files are generated:

![incgenfiles](https://cloud.githubusercontent.com/assets/13046720/8378913/d23d8d52-1c1c-11e5-8e63-4895e542114b.PNG)

This is a major drawback with this tool and that is the only reason why we can't use this tool in the project that I'm currently working with. We have lots of JSON objects that are present in many method bodies and we cannot have the object definition in every single body. It would be too costly to maintain. 

We don't intend to specify all schemas in the RAML as in the example file above. We plan to have them in separate files and include them in to the RAML file. The example schema was just written to pin point the problem that we experience. We would like the RAML file to look like this and have the JSON schemas outside the RAML contract file:

![capture](https://cloud.githubusercontent.com/assets/13046720/8379236/e08362fe-1c1e-11e5-8693-be8fb49313af.PNG)

**Comment by pzsembik** [comment]
We are running into similar issues. Any timeline for when this will be added in the next release?

**Comment by woodp** [comment]
@olssochk thank you for the detailed explanation

I have already addressed this specific case, changes will be bundled in next release, coming soon (next week)

@pzsembik could you please provide a sample ?

**Comment by pzsembik** [comment]
When this is defined in the schemas section:
 "policy": '{"type":"object","title":"policy","properties":{"policyNumber":{"type":"string","required":true,"title":"policyNumber"},"collision":{"type":"boolean","required":false,"title":"collision"},"liability":{"type":"boolean","required":false,"title":"liability"},"roadSideAssistance":{"type":"boolean","required":false,"title":"roadSideAssistance"},"preminum":{"type":"number","required":false,"title":"preminum"},"effectiveStartDate":{"type":"string","required":false,"title":"effectiveStartDate"},"effectiveEndDate":{"type":"string","required":false,"title":"effectiveEndDate"},"drivers":{"type":"array","required":false,"title":"drivers","items":{"type":"object","$ref":"#/schemas/driver"},"uniqueItems":false},"vehicles":{"type":"array","required":false,"title":"vehicles","items":{"type":"object","$ref":"#/schemas/vehicle"},"uniqueItems":false},"paymentHistory":{"type":"array","required":false,"title":"paymentHistory","items":{"type":"object","$ref":"#/schemas/payment"},"uniqueItems":false}}}'

The RAML Generator does not create the $ref models in VS 2013. Just the controllers.

When this definition is fully defined in the schemas section:
 "policy": '{"type":"object","$schema": "http://json-schema.org/draft-03/schema","id": "http://jsonschema.net","required":false,"properties":{ "collision": { "type":"string", "id": "http://jsonschema.net/collision", "required":false }, "drivers": { "type":"array", "id": "http://jsonschema.net/drivers", "required":false, "items": { "type":"object", "id": "http://jsonschema.net/drivers/0", "required":false, "properties":{ "dateOfBirth": { "type":"string", "id": "http://jsonschema.net/drivers/0/dateOfBirth", "required":false }, "driverId": { "type":"string", "id": "http://jsonschema.net/drivers/0/driverId", "required":false }, "driverLicense": { "type":"string", "id": "http://jsonschema.net/drivers/0/driverLicense", "required":false }, "firstName": { "type":"string", "id": "http://jsonschema.net/drivers/0/firstName", "required":false }, "lastName": { "type":"string", "id": "http://jsonschema.net/drivers/0/lastName", "required":false }, "address": {"type":"object","title":"address","properties":{"addressLine1":{"type":"string","required":false,"title":"addressLine1"},"addressLine2":{"type":"string","required":false,"title":"addressLine2"},"municipality":{"type":"string","required":false,"title":"municipality"},"stateCode":{"type":"string","required":false,"title":"stateCode"},"postalCode":{"type":"integer","required":false,"title":"postalCode"},"postalExtensionCode":{"type":"integer","required":false,"title":"postalExtensionCode"}}},

The drivers type also has a $ref to address.
The RAML Generator creates the correct models in VS 2013 when all $refs are fully defined in the schema.

So the code gen needs to create models from $refs and $refs inside of $refs.

**Comment by dmalanij** [comment]
+1
I've been the whole afternoon trying to make a reference work for a client generation. Every way I've tried ended up with a comment in the generated cs file saying

```C#

    // Unable to parse the following Schemas. Please note that JSON Schema version 4 is not supported
    // Liga - Could not parse JSON Schema. v3 parser message: Could not resolve schema reference 'ParticipanteLiga'.. v4 parser message: Could not resolve schema reference 'ParticipanteLiga'.
    // /Ligas-getOKResponseContent - Could not parse JSON Schema. v3 parser message: Could not resolve schema reference 'ParticipanteLiga'.. v4 parser message: Could not resolve schema reference 'ParticipanteLiga'.
    // /Ligas/{anio}-getOKResponseContent - Could not parse JSON Schema. v3 parser message: Could not resolve schema reference 'ParticipanteLiga'.. v4 parser message: Could not resolve schema reference 'ParticipanteLiga'.
```
I also tried setting the id for the schema as specified in json schema but no luck.

**Comment by woodp** [comment]
fixed in last release

Note that the way to do this is to use the RAML schema key in the JSON schema, just as in the sample provided by @olssochk

**Comment by engxladso** [comment]
@woodp Our installation uses Visual Studio 2013. The net result of importing the package into VS is that we have RAML.Api.Core version 0.9.7. Does this include your fix for this issue? The reason I ask is that we are experiencing both issues mentioned here in that models are not created if an include file containing includes for multiple schemas is used in the RAML def. Also we are finding that nested objects are ignored.

**Comment by woodp** [comment]
This fix for this issue has been released, but there's a closely related one (issue #59) that has not been released yet.
You can provide the RAML so I can test against or wait for next release (coming soon)
