### ISSUE TITLE
Command line tools not picking up RAML include files in relative folders when referenced by a path in the command line

### ISSUE THREAD

**Issue by ageoghegan** [mulesoft-labs/raml-dotnet-tools#134]
I have an api.raml file which includes a baseTypes.raml file from a relative folder called "library".
Like so:
```
...
uses:
  Requests: library/requests.raml
  Responses: library/responses.raml
  Base: library/baseTypes.raml
...
```
When I invoke the command line generator with the following command line:
**RAMLGen server -d .\API -s "C:\Users\ageoghegan\Documents\xyz\product\api.raml" -w**

I get the following fault:
_Error: Could not find file 'C:\Users\ageoghegan\Documents\xyz\product\baseTypes.raml'_

It's obviously not adding the relative folder for the include.

**Comment by woodp** [comment]
Thanks for the feedback, fix will be included in next release

**Comment by wis3guy** [comment]
I ran into the same problem.

**Comment by wis3guy** [comment]
@woodp I am really glad this made it into the next release! Any idea when this will be released?

**Comment by ageoghegan** [comment]
The chap who responded was a bit vague about that. I've been watching for developments, but if it's not resolved soon I'll have to flatten my file structure.

Anthony Geoghegan
Senior .Net Architect
8 West Consulting

M: +353 (0)87 226 4847

Sent from my iPhone
________________________________

**Comment by woodp** [comment]
I updated the CLI Tool, you can [download it here](https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/command-line)

**Comment by wis3guy** [comment]
@woodp You just made my day!

**Comment by ageoghegan** [comment]
Thanks Pedro.

Anthony Geoghegan
Senior .NET Framework Architect
8 West Consulting

P: +353 (0)21 492 5129
M: +353 (0)87 226 4847
E: ageoghegan@8west.ie<mailto:ageoghegan@8west.ie>
W: www.8west.ie<http://www.8west.ie/>
L: https://ie.linkedin.com/in/anthony-geoghegan-a4aa6418
[cid:image001.png@01D26781.0C8F84A0]

Building 1, University Technology Centre,
Curraheen Road, Cork, TY12 AY18, Ireland.

**Comment by wis3guy** [comment]
@woodp I tried to run this on my WIndows 10 Machine, with both Visual Studio 2015 and 2017 installed. This is the result:

~~~
RAMLGen.exe server -s ..\finance-api.raml
Error: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
~~~

On my machine i can find the following assemblies:

* Microsoft.VisualStudio.TextTemplating.Interfaces.14.0.dll
* Microsoft.VisualStudio.TextTemplating.Interfaces.11.0.dll
* Microsoft.VisualStudio.TextTemplating.Interfaces.10.0.dll

Some googling taught me that v12 came with VS2013. As the assembly name is different, as well as the public key, i cannot create a binding redirect. I can also not download this particular version via nuget.

Could you either include the assembly in the zip file _or_ update the code to use a more recent version of the templating engine?

**Comment by ageoghegan** [comment]
This sounds like a newly introduced bug. I have VS 2013 installed so I didn't see it.

Anthony Geoghegan
Senior .Net Architect
8 West Consulting

M: +353 (0)87 226 4847

Sent from my iPhone
________________________________
