### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by PaulJoW** [mulesoft-labs/raml-dotnet-tools#136]
Hi,

Are there plans for a Visual Studio 2017 version?
If so, when do you think we could expect a release?

Many Thanks,
Paul

**Comment by wis3guy** [comment]
I would also like to be able to use the extension from VS2017.

**Comment by timcromarty** [comment]
Same here. I cannot use RAML until I have full VS2017 and .Net Core support

**Comment by wis3guy** [comment]
@timcromarty I opted to using the CLI tool (RAMLGen) which does have Core support.

**Comment by timcromarty** [comment]
I am not trying to generate a RAML Client, I want to generate RAML from the .NET Core (web API) application

**Comment by rstraszewski** [comment]
This is also huge problem for our company - please provide support for vs2017

**Comment by integrationpoint** [comment]
Plus one on the VS2017 support...

**Comment by tb-wwparker** [comment]
I'd also like to upgrade to VS2017 and the RAML tools are my largest blocker for moving.

**Comment by laoueib** [comment]
Do we know if it is scheduled or not ?

**Comment by asfdev** [comment]
I also need support for VS17.

**Comment by woodp** [comment]
VS 2017 is under way

**Comment by ModernRonin** [comment]
also very interested in VS2017 support, thanks!

**Comment by jfernandezrico** [comment]
I need RAML tools for .Net Core in VS2017. Thank you!

**Comment by sichvoge** [comment]
Hi, I am locking this conversation. As @woodp already said, it is under way! No worries, we hear you. ;)
