### ISSUE TITLE
Automate as a pre-build step

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/raml-dotnet-tools#138]
Is there a way to automate the class generation either WebApi or aspnet Core as part of a build process?

**Comment by woodp** [comment]
Yes, you can use the [command line tools](https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/MuleSoft.RAMLGen#raml-generator---command-line-tools)

**Comment by wis3guy** [comment]
@woodp Thanks for pointing me here. Fail on my part for not reading through all the docs before asking a question. How do i get the ZIP file described in the installation instructions? I tried to build the solution locally, but i lack the Visual Studio assemblies. Guess i need to install some SDK first ...

**Comment by woodp** [comment]
Yes, sorry, I meant to send you this link: https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/command-line

**Comment by wis3guy** [comment]
Thank you!
