### ISSUE TITLE
Running the CLI tool with -o triggers a confirmation box

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/raml-dotnet-tools#143]
#
![confirm](https://cloud.githubusercontent.com/assets/6885003/24829283/00bb061a-1c6f-11e7-8a4b-151664e2a5d0.png)
When running the CLI tool, i still get a confirmation box for an include file (library). As a result, i cannot run this as part of my build process.

Expected behavior with the -o flag would be **silent** overwriting.

Note: This is related to the fix to #134

**Comment by woodp** [comment]
This is the other way round, -o will ask for confirmation, without -o will overwrite silently (because actually is confirm overwrite, not overwrite). 
I will fix this but in the meantime just use without -o
