### ISSUE TITLE
Model generation does not handle explicit string arrays correctly

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/raml-dotnet-tools#144]
Message:
~~~
Error: Object reference not set to an instance of an object.
~~~

Input RAML:
~~~
#%RAML 1.0

title: Bug report

/foo:
  put:
    body:
      application/json:
        properties:
          bar:
            type: array
            items: string
~~~

According to the spec (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#array-type) this is a valid specification.

**Comment by woodp** [comment]
Moving to parser repo
https://github.com/raml-org/raml-dotnet-parser-2/issues/11
