### ISSUE TITLE
Response type defaults to `string`

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/raml-dotnet-tools#147]
For some reason, the controller method generator defaults to `string` as the response type when no response type is specified in the RAML document. Especially for `POST` and or `DELETE` scenarios this can be problematic.

Common practice in RESTful API design:

* is for `DELETE` operations to respond with a `204 NO CONTENT` status code and an empty body.
* is for `POST` operations to respond with a `201 CREATED` status code, an empty body and a location header.

In both scenarios defaulting to `string` just doesn't make sense.

**Comment by woodp** [comment]
The generated method (controller action) will be **public async Task\<IHttpActionResult\>** or **public IHttpActionResult** (depending if you chose async or not).
which let's you return any status code you like in the implementation (which is up to the dev).

So, we are not preventing you from using common practices in your restful api design =)

But, if you are you planning to use a custom template, then having a different response type would give you more info yes, so I will check this.

**Comment by woodp** [comment]
I'm closing this because it's encompassed in your other request to have [more info in the T4](https://github.com/mulesoft-labs/raml-dotnet-tools/issues/148)

**Comment by wis3guy** [comment]
@woodp I'm not 100% in agreement that the other issue replaces this one. I do agree that there is some overlap. 

* This issue is about the __model__ type that is returned by the implementation. Currently, if i **do not** specify a body in the RAML, it defaults to `string`. Imho it should default to `void` in that case.
* Issue #148 is about reflecting the various response codes defined in the RAML spec in the generated code.
