### ISSUE TITLE
More details passed into T4 templates

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/raml-dotnet-tools#148]
The information that is passed into the T4 templates is quite opinionated and therefore pretty limited. The generator decides upfront what information is passed into the T4 templates which generate controllers, by constructing `ControllerObject` instances.

Ideally i would have access to __all__ the information specified in the RAML document, for each resource. That way i could wrap `try/catch` clauses around the actual _meat_ of the methods and respond with the specified (RAML) status codes.

Assume this RAML snippet:

~~~
/styles:
  post:
    body:
      application/json:
        properties:
          name:
            type: string
            required: true
    responses:
      201: 
        description: The style is created
      400:
        description: Invalid style name
        body:
          application/json:
            type: Lib.Error
     409:
        description: Duplicate style name
        body:
          application/json:
            type: Lib.Error
~~~

Right now, the T4 template has no notion of the various responses specified for the `POST`. By default, for aspnet core it defaults to returning `Ok()` for all controller methods. But, that means an `HTTP 200 OK` response is returned to the client. 

In order to generate code that actually does what is specified by the RAML, my conventions need to be implemented both in the T4 templates __and__ in the RAML spec. No guarantees that the two are in sync, which is bad.

If we have more information passed into the T4 template, we could generate a base controller that would look something like:

~~~c#
try
{
    Uri uri = // call implementation method
    return Created(uri, null);
}
catch(InvalidStyleNameException e)
{
    return StatusCode(e.StatusCode, new LibError(e.StatusCode, e.Message));
}
catch(DuplicateStyleNameException e)
{
    return StatusCode(e.StatusCode, new LibError(e.StatusCode, e.Message));
}

// Let the default exception handler deal with any other exception ...
~~~

Note that imho it would also make sense to generate exceptions for all non-success status codes, specified for any of the resources in the RAML file. Otherwise, how would the implementation signal a specific error?

Something like:

~~~c#
public class InvalidStyleNameException : Exception
{
    public InvalidStyleNameException() : base("Invalid style name")
    {
    }

    public const StatusCode = 400;
}

public class DuplicateStyleNameException : Exception
{
    public DuplicateStyleNameException() : base("Duplicate style name")
    {
    }

    public const StatusCode = 409;
}
~~~

**Comment by woodp** [comment]
Thanks for the feedback, I'll think about this.
