### ISSUE TITLE
RAMLGen: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.12.0

### ISSUE THREAD

**Issue by Grauenwolf** [mulesoft-labs/raml-dotnet-tools#150]
C:\Source\dotnet-raml-test>RAMLGen\RAMLGen.exe  server -s  api.v1.raml -d AspDotNet\Controllers
Error: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

This machine is running Visual Studio 2017.

**Comment by tb-wwparker** [comment]
When I tried building the project using VS 2017, this was one of the errors that I had. I believe that Microsoft changed the assembly from version 12 to version 14 or 15 in VS 2017. Either you need to install an older version of Visual Studio, or wait for the VS 2017 solution file to be be released/ported.

**Comment by Grauenwolf** [comment]
Honestly, I've given up on this project. It's basically useless until they get a real RAML parser for .NET instead of the hacked together Node interopt they are currently using. 

I'd try to fix this, but Visual Studio chokes on trying to deal with their dependency chain. Really, what kind of person thinks shoving all of Node into a .NET package is a good idea?

**Comment by wis3guy** [comment]
I actually had the same problem, and came up with the following workaround.

https://github.com/wis3guy/raml-dotnet-tools/commit/4e0c9bbfcdeb15b1c48fc49273878d24fb9a85d4

**Comment by woodp** [comment]
I updated RAMLGen https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/command-line
Visual Studio dependencies were removed. vc++ redistributable package and .net framework are the only requisites now.
