### ISSUE TITLE
Unable to cast object of type 'System.Dynamic.ExpandoObject' to type 'System.String'

### ISSUE THREAD

**Issue by drobison** [mulesoft-labs/raml-dotnet-tools#152]
I am receiving the following error when trying to import a RAML v1.0 file:
`Unable to cast object of type 'System.Dynamic.ExpandoObject' to type 'System.String'
`
I noticed this bug has previously been closed https://github.com/mulesoft-labs/raml-dotnet-tools/issues/85.

**Comment by woodp** [comment]
that error can have many different reasons.
could you provide a RAML sample to reproduce the error ?
