### ISSUE TITLE
String array properties not generated #111 is not fixed

### ISSUE THREAD

**Issue by dbelchenko** [mulesoft-labs/raml-dotnet-tools#153]
Release 2.0.6 notes says that issue #111 is fixed.
However the tool generates type `string` instead of `IList<string>.`

CopyRecipientEmail?: string[] 
generates to
public string CopyRecipientEmail { get; set; }

**Comment by woodp** [comment]
111 is a different issue
this is a duplicate of https://github.com/mulesoft-labs/raml-dotnet-tools/issues/145
