### ISSUE TITLE
Missing support for queryString

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/raml-dotnet-tools#156]
Uri parameters defined like this, are not generated for the API:

~~~
#%RAML 1.0

title: Sample RAML

types:
  address: string
  coordinates:
    properties:
      lat: number
      long: number
  date:
    type: datetime
    required: false
  country_code: string
  city_name: string

/foo/{bar}:

  /baz:

    get:
      queryString:
        type: [address | coordinates, date, country_code, city_name]
      responses:
        200:
          body:
            application/json:
              type: Qux[]
~~~

For certain resources, this declaration is preferable over `queryParameters` (the two methods are mutually exclusive according to the spec) as it allows two parameters to be mutually exclusive.

See: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#query-strings-and-query-parameters

In addition i find that the RamlGen tool generates model classes for the `types` that are part of the `queryString`, which is imho useless.

**Comment by woodp** [comment]
Parser equivalent: https://github.com/raml-org/raml-dotnet-parser-2/issues/18
