### ISSUE TITLE
Add RAML reference fails if solution is not on drive C:

### ISSUE THREAD

**Issue by laugel** [mulesoft-labs/raml-dotnet-tools#16]
It seems that files linked by the RAML file are downloaded inside the solution, and then accessed with absolute path without the drive letter (and so assuming they are on drive C:).

In that example my solution is on drive D:, but the product is trying to access the downloaded files from drive C :
![image](https://cloud.githubusercontent.com/assets/5048661/8722562/257a86ce-2bc6-11e5-9e36-4db5acdc2172.png)

**Comment by woodp** [comment]
Fix will be included in next release.
Thanks for the feedback.

**Comment by dmalanij** [comment]
+1 for this

**Comment by woodp** [comment]
fixed in last release
