### ISSUE TITLE
Getting System.Dynamics.ExpandoObject to type "System.String Error message

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#161]
In #85 there was an issue where the application threw an error that said can't cast object of type System.Dynamics.ExpandoObject to type "System.String Error message. We seemed to have hit it.

The RAML file is attached. 
Is there something we can change in the RAML to get it to import while we wait for a fix?

[Service-Test.txt](https://github.com/mulesoft-labs/raml-dotnet-tools/files/1058927/Service-Test.txt)

**Comment by woodp** [comment]
Moved to the parser: https://github.com/raml-org/raml-dotnet-parser-2/issues/16
