### ISSUE TITLE
any type

### ISSUE THREAD

**Issue by abbasvahdani** [mulesoft-labs/raml-dotnet-tools#162]
I have an issue regarding dealing with 'any' data type in RAML.

Clearly I put my data type to be 'any' and the exception is a property with type of 'object' would be generated, but that property is skipped and the remaining property of the class is generated properly. 

If you handle this issue it would be great and we can use this trick very flexibly to map many data types including Dictionary or Sorted Dictionary

Regards,
Abbas

**Comment by jfernandezrico** [comment]
I'm testing this command line tool with jukebox-api.raml sample and this tool doesn't transform << text inside >> inside controllers code.

/// RAML code

resourceTypes:
  - collection:
      description: Collection of available <<resourcePathName>> in Jukebox.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>

-------------

/// C# code

/// <summary>
/// Get a list of &lt;&lt;resourcePathName&gt;&gt;. - /artists
/// </summary>
/// <param name="query">JSON array [{&quot;field1&quot;,&quot;value1&quot;,&quot;operator1&quot;},{&quot;field2&quot;,&quot;value2&quot;,&quot;operator2&quot;},...,{&quot;fieldN&quot;,&quot;valueN&quot;,&quot;operatorN&quot;}] &lt;&lt;description&gt;&gt; </param>
		/// <param name="orderby">Order by field: &lt;&lt;fieldsList&gt;&gt; </param>
		/// <param name="order">Order</param>
		/// <param name="offset">Skip over a number of elements by specifying an offset value for the query</param>
		/// <param name="limit">Limit the number of elements on the response</param>
        public async Task<IActionResult> Get(string query = null,string orderby = null,string order = null,int? offset = null,int? limit = null)
        {
            // TODO: implement Get - route: artists/
			return new ObjectResult("");
        }

**Comment by woodp** [comment]
@abbasvahdani 'any' is converted to 'object', see https://github.com/mulesoft-labs/raml-dotnet-tools/blob/6dc756027be825f746b89f726474688c171bdbfc/Raml.Tools/NetTypeMapper.cs#L84

If you have a case where this is not working as expected please provide a RAML sample to reproduce it
