### ISSUE TITLE
Source is empty.

### ISSUE THREAD

**Issue by marpit** [mulesoft-labs/raml-dotnet-tools#166]
RAML tool remove source after files are regenerated or api client is imported. Source attribute is empty in ref file. For example update client is impossible. If I click right mouse button on raml file and select edit raml properties, source is empty in dialog window too. If I set path, source is empty again. 

`// do not edit this file
source: 
namespace: MyWebApi
client: MyWebApiClient`

**Comment by woodp** [comment]
yes, source will only be present when it's a web reference (http...)
When you edit the API spec (.raml) file it will regenerate the code. You can also remove the RAML/OAS reference and create it again.
