### ISSUE TITLE
in some cases the content is not sent to the server with put and post requests

### ISSUE THREAD

**Issue by ddjansen** [mulesoft-labs/raml-dotnet-tools#168]
The client proxies are generated using the T4 template RAMLClient.t4. There is a bug in this section near line 342. In the last else clause of the code snippet the incoming content is not passed on to the "req" object that is sent to the server. The result is an http 400 message stating that the body should contain content.

                if (method.Verb != null && method.Verb != "Delete" && method.Verb != "Get")
                {

	                if (method.Parameter == null || method.Parameter.Type == "string")
	                {
#>
            req.Content = request.Content;
<#
	                }
	                else
	                {
                        if(method.RequestContentTypes.Any(c => c.Contains("xml")) && !method.RequestContentTypes.Any(c => c.Contains("json"))){
#>
            var stringWriter = new StringWriter();
        	new XmlSerializer(typeof (Models.<#= method.Parameter.Type #>)).Serialize(stringWriter, request.Content);
            req.Content = new  StringContent(stringWriter.GetStringBuilder().ToString(), Encoding.UTF8, "application/xml");     
<#
                        } else {
#>
	
///////no content transferred to the  request object req!!!                  
            if(request.Formatter == null)
                request.Formatter = new JsonMediaTypeFormatter();
<#
                        }
	                }
                }

**Comment by ddjansen** [comment]
I think that adding the following line to the last else clause solves the problem:
	req.Content = new ObjectContent(typeof(<#= method.QualifiedParameterType #>), request.Content, new JsonMediaTypeFormatter());

**Comment by woodp** [comment]
fixed in the latest relase
