### ISSUE TITLE
'allOf' construct in json types is ignored

### ISSUE THREAD

**Issue by ddjansen** [mulesoft-labs/raml-dotnet-tools#174]
Below is a simplified version of the json schema that is used. From this json schema the model is generated but it does not contain any of the properties of the BusinessModelObject which it should inherit. 
{
    "definitions": {
        "BusinessModelObject": {
            "id": "BusinessModelObject",
            "description": "Version: 0.1",
            "type": "object",
            "properties": {
                "apgId": {
                    "description": "Unique identifier of the Object",
                    "type": "integer"
                },
                "RegistratieDatum": {
                    "type": "string"
                },
                "vervallenDatum": {
                    "type": "string"
                },
                "mogId": {
                    "description": "Unique identifier of the different funds registered within APG",
                    "type": "string"
                },
                "rootObjectType": {
                    "description": "Indication of the BOT type of the object. Example: Overeenkomst, Opdrachtgever, etc",
                    "type": "string"
                }
            }
        }
    },

    "type": "object",
    "allOf": [
        {
            "$ref": "#/definitions/BusinessModelObject"
        }
    ],
    "properties": {
        "rolOmschrijving": {
            "type": "string"
        },
        "typeOmschrijving": {
            "type": "string"
        }
    }
}
Apparently the allOf section is completely ignored by the generation tool.

**Comment by woodp** [comment]
This was already addressed and will be available in next release
