### ISSUE TITLE
Compiler error: member names cannot be the same as their enclosing type

### ISSUE THREAD

**Issue by PolarbearDK** [mulesoft-labs/raml-dotnet-tools#182]
When generating: https://raw.githubusercontent.com/raml-apis/GitHub/master/api.raml

public partial class  Key 
{
	[JsonProperty("key")]
        public string Key { get; set; } <--- Key property not allowed in class Key.
...
}

**Comment by woodp** [comment]
This is addressed in the new tool. You can check the beta version here: https://github.com/mulesoft/amf-dotnet-tools/releases/tag/v0.0.1-beta
