### ISSUE TITLE
Update RAML References not showing

### ISSUE THREAD

**Issue by dfdumaresq** [mulesoft-labs/raml-dotnet-tools#183]
I'm unable to display the menu option for updating my RAML document after right-clicking on the .raml file.

I'm running MS VS 15.5.7 with the 2.1 RAML Tools extension. 
Notice the About below says 1.0, but the Tools and Extensions further down says 2.1
![image](https://user-images.githubusercontent.com/20051/36924064-15ecc87e-1e22-11e8-8c34-a3fe27afb381.png)

![image](https://user-images.githubusercontent.com/20051/36924142-65548ffa-1e22-11e8-97d0-f7a291d23f46.png)

**Comment by woodp** [comment]
That option is no longer available. If you update your RAML code will be regenerated on save.
