### ISSUE TITLE
Abstract class generated with no properties

### ISSUE THREAD

**Issue by gavinburge** [mulesoft-labs/raml-dotnet-tools#185]
I have a RAML definition with nested types which are defined in the Raml in alphabetical order e.g. Applicant, BankInformation etc where Applicant has a property called Bank details which is a BankInformation type i.e. Applicant depends on BankInformation.

The issue:
When generating code, Applicant is defined as an abstract class with no properties on it, which I think is because it doesn't yet know about the types Applicant needs e.g. BankInformation.

I confirmed this in the T4 template by outputting all of the properties of each type and Applicant is blank.

If I were to move Applicant below BankInformation in the definition it will create Applicant as a partial with BankInformation as a property, Im guessing because it's processed BankInformation before Applicant and knows what it is.

Unfortunately I can't edit the Raml definition to get this to work as it's defined by a third-party.

Is there a work around for this? Is it a bug or am I missing something?

**Comment by rkralston** [comment]
All my abstract classes are empty.
