### ISSUE TITLE
Only first path of RAML is imported when entire file is indented

### ISSUE THREAD

**Issue by ryanlaws** [mulesoft-labs/raml-dotnet-tools#188]
# Description
I am fairly new to RAML so I apologize if my terminology is wrong. I received a RAML definition from a client containing a number of imports. These imports all have a base level of indentation of one indentation-unit / two spaces.

I expect all paths contained in the import to load. However, I observe that only first path of the imported RAML is actually present in the import window or the generated C# code.

The client indicated that the RAML is working as expected in Anypoint Studio.

# Expected
All paths contained in an imported RAML file with a base level of indentation are loaded. 

# Observed
Only first path contained in an imported RAML file with a base level of indentation is loaded. 

# Version
2.1.0

# Example
## Root:
```raml
/baz:    !include baz.raml
```
## Import (baz.raml):
```raml
# Note the indentation - only /foo will import
  /foo
    get:
    # ...
  /bar
    get:
    # ...    
```

**Comment by woodp** [comment]
could you please provide a simple RAML spec where this is reproducible ?
