### ISSUE TITLE
Missing "Add RAML contract" .Net Core 2.0 WebApi - VS2017

### ISSUE THREAD

**Issue by fabus1989** [mulesoft-labs/raml-dotnet-tools#189]
Hi,

I cannot generate a RAML definition from ASP .NET Core WebAPI, due to missing "Add RAML contract".

Visual Studio Enterprise 2017 15.7.1
Raml Tools for .NET - 2.1.0
Project .NET Core 2.0 WebApi

![image](https://user-images.githubusercontent.com/32595854/39810340-edb139ba-5384-11e8-9c04-91191e90fd2e.png)

**Comment by woodp** [comment]
that feature is only available for .json / .xproj project types

**Comment by woodp** [comment]
@fabus1989 
This is addressed in the new tool. You can check the beta version here: https://github.com/mulesoft/amf-dotnet-tools/releases/tag/v0.0.1-beta
