### ISSUE TITLE
Relative paths to included files not supported

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#19]
When you are creating a RAML contract in your WebAPI application, included files must be referenced with the absolute path preventing the solution to be edited in different workspaces by different people.

### Example
```RAML
#%RAML 0.8
title: "API de Ejemplo de Morphe"
version: "v1"
baseUri: "/{version}"
schemas: 
    - Equipo: !include includes\equipo.json
    - Liga: !include includes\liga.json
    - ParticipanteLiga: !include includes\participanteLiga.json
resourceTypes:
  - base: !include includes\base.raml
  - coleccion: !include includes\coleccion.raml
  - item: !include includes\item.raml
# ...
```
*Sorry about the spanish in the example*
### Output
![image](https://cloud.githubusercontent.com/assets/13454997/8831710/7865e710-30a4-11e5-966f-77e9def3cb83.png)

This seems to be quite related with issue #16. It's really a shame relative sources can't be used as it can be done with the online API Designer.

Thanks in advance

**Comment by dmalanij** [comment]
I guess this is also related. A similar issue occurs with the .ref file that's created after adding (through the Upload functionality) a RAML contract to your project. 

The file originally specifies absolute routes:
```
// do not edit this file
source: c:\Dev\MyProject\RAMLSource\api.raml
namespace: MyProject.Web.Api
```

Despites the warning, tried to set a relative source:
```
// do not edit this file
source: .\RAMLSource\api.raml
namespace: MyProject.Web.Api
```
And ended up with the following error:
![image](https://cloud.githubusercontent.com/assets/13454997/8985614/916b972a-36d8-11e5-9cbe-d1c8be386296.png)

The weird thing is that I've tried the same with the Movies project that comes with the samples and worked out fine:
```
// do not edit this file
source: .\movies.raml
namespace: MoviesWebApi2Sample.Movies
```
Any ideas?

Solving this and #24 would allow to suppor truly collaboration on projects depending upon RAML references.

**Comment by woodp** [comment]
Paths in included files are now relative
