### ISSUE TITLE
Sample of Targeted Code

### ISSUE THREAD

**Issue by rkralston** [mulesoft-labs/raml-dotnet-tools#191]
I understand a new release is pending. 

It would be nice if you included a sample demonstrating the desired generated code (similar to what OAS provides).

This would allow us to provide better feedback if we get something different (e.g. it doesn't appear that empty abstract classes are a big deal). We would also be able to manually fix any problematic code that gets generated.

**Comment by woodp** [comment]
You can find samples here: https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/samples
