### ISSUE TITLE
Error with RAML spec

### ISSUE THREAD

**Issue by aspengler** [mulesoft-labs/raml-dotnet-tools#192]
When trying to add a RAML contract in "VS 2017 Community Edition" with version 2.1.0, the error "Object reference not set to an instance of an object." pops up and no code is created...

**Comment by woodp** [comment]
@aspengler can't reproduce this with latest version, reopen otherwise

**Comment by aspengler** [comment]
Tried the newest version 2.1.1. with the attached file - still getting this error.

[trck_api_spec_in_raml-1.0_v1.raml.txt](https://github.com/mulesoft-labs/raml-dotnet-tools/files/2376278/trck_api_spec_in_raml-1.0_v1.raml.txt)

**Comment by woodp** [comment]
working with the latest preview version
