### ISSUE TITLE
Custom types not used as properties

### ISSUE THREAD

**Issue by handflucht** [mulesoft-labs/raml-dotnet-tools#193]
I have a RAML-spec made of three files:

- api.raml
- user.raml
- common.raml

api.raml:
```
#%RAML 1.0
title: TestApi
version: v1
protocols: [ HTTPS ]
baseUri: http://localhost:8080/testapi/api/
mediaType: application/json

uses:
user: ./user.raml
  common: ./common.raml

/users:
  description: |
        Users endpoint
  get:
        description: |
            Retrieves all existing users
        responses:
          200:
            body:
              application/json:
                type: user.UserDto
```

user.raml
```
#%RAML 1.0
title: some title

uses:
  common: ./common.raml

types:
  UserDto:
    description: Common user
    properties:
      firstname: string
      lastname: string
      relationval: common.relation
```

common.raml
```
#%RAML 1.0

title: some title
types:
  relation:
    type: string
    enum: [int, ext]
```

As you can see, in the user.raml a type UserDto is defined which makes usage of the common.relation-type at the relationval-property.
This property isn't generated at all. Instead the following code is generated:

```
   public partial class  UserUserDto 
    {

		[JsonProperty("firstname")]
        public string Firstname { get; set; }


		[JsonProperty("lastname")]
        public string Lastname { get; set; }
}

```

**The whole property is missing. If I change the type of the property relationval to string, the property is generated succesfully.** 

Anybody some help how to fix this?

**Comment by josep-bocanegra** [comment]
> this is most probably related to [this](https://github.com/mulesoft-labs/raml-dotnet-tools/issues/178), will check it

I don't know if it is something related to issue #178 but I have the same problems as @handflucht 

I have updated from version 2.1.0 to 2.1.2 and suddenly all the properties of type enum doesn't get generated.

I have realised that when the ApiModel.t4 iterates through the properties of apiObject, apiObject.Properties contains all the properties of the object except the ones that are of type enum.

These are the ramls I have used to reproduce the problem:

Contact.raml
```
#%RAML 1.0
title: Contacts app

uses:
  Aux: includes/auxiliar.raml

types:
  Contact:
    type: object
    properties:
      name:
        type: string
      gender:
        type: Aux.Gender
    example:
      name: John
      gender: Male
/contacts:
  get:
    responses:
      200:
        body:
          application/json:
            type: Contact

```
auxiliar.raml
```
#%RAML 1.0 Library

types:

  Gender:
    description: Gender - either male or female
    enum:
      - Male
      - Female

```

I hope this could help.

Thank you.

**Comment by woodp** [comment]
this is solved in the latest release

@handflucht please note that when using "uses" you need to declare the external file as a **library**.
The first line of the library should include this: #%RAML 1.0 Library
Please take a look at how @josep-bocanegra did in his sample
