### ISSUE TITLE
Regarding issue #185 - Empty abstract classes

### ISSUE THREAD

**Issue by ScottMartin67** [mulesoft-labs/raml-dotnet-tools#195]
Issue #185 is stated as closed and we were specifically told it would address our problem. I have updated to version 2.1.1 but I am still experiencing the problem that the abstract classes are generating empty. 

Is there a further update to this?

**Comment by woodp** [comment]
Could you provide a RAML to reproduce the error?

**Comment by ScottMartin67** [comment]
Hi Pedro, thanks for getting back to me so quickly. I can't share the RAML as it is owned by a third party but I will try and get their incident number when they reported the issue originally to the product manager at Mulesoft. Thanks

**Comment by woodp** [comment]
any RAML where this happens will work
