### ISSUE TITLE
Properties of the model classes do not have validation attributes

### ISSUE THREAD

**Issue by majkimester** [mulesoft-labs/raml-dotnet-tools#198]
The Property class already has CustomAttributes propery which can be added to the template to generate Required, MinLength, MaxLength and Range attributes. This should be added to the default template (to model properties, header properties and response properties as well):

`using System.ComponentModel.DataAnnotations;
`
...
```
		string customAttributes = property.CustomAttributes;
		if(!string.IsNullOrWhiteSpace(customAttributes))		
		{
#>
<#= customAttributes #>
<#		}
```

**Comment by woodp** [comment]
Thanks for the feedback. These attributes are on the asp.net (server) templates.
They are not present on the client template. How are you going to use them on the client ?

**Comment by majkimester** [comment]
Hello,

I already added the CustomAttributes to my RAMLClient.t4 template, but I think it will be useful to add it the default RAMLClient.t4 template. If you have different opinion just close this ticket.

I am going to validate the data according to these attributes before I send them to the server.
For example if a user fill a form (e.g name, address, etc.) and the client will not allow to submit the data until all required fields are not filled or not valid. In that way the RAML definition would be the single place where I need to define if a field is required or its limits (not in the client code by hand).

Currently only the length, min/max value validation is possible, but for some property a regex would be required, e.g account number. Is it possible to add it also to the Property class in raw format as it defined in the RAML file? (In that way a custom template can do something with it, you don't need to convert it.)

Br.

**Comment by woodp** [comment]
@majkimester 
This is addressed in the new tool. You can check the beta version here: https://github.com/mulesoft/amf-dotnet-tools/releases/tag/v0.0.1-beta
