### ISSUE TITLE
Universal Apps not supported

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#20]
I was trying to reference a RAML service from a Windows 8.1 application project but, after recognizing the resources to be included, the process fails as the platform is not supported.

![image](https://cloud.githubusercontent.com/assets/13454997/8870634/bad85820-31ef-11e5-9016-fffc98929f60.png)

I've forked the project, made a branch and started working on making the RAML.Api.Core a portable class library, shouldn't be much trouble as Core functionality is not doing anything platform specific. You can check it on https://github.com/dmalanij/raml-dotnet-tools/tree/feature/portableSupport

**Comment by fedebongio** [comment]
Diego, world is very small.

**Comment by dmalanij** [comment]
Very small indeed!!! Sent you an email (I think)... if you got it write back ;)

**Comment by pcibraro** [comment]
Hi Diego,

Could you send a pull request once it's done ?. We would love to add this windows phone support to the tools. 

Thanks

**Comment by dmalanij** [comment]
Sure, happy to contribute that way.
The real important changes are already committed but had been working on some further stuff for the nuget packaging. I'll probably work tomorrow on testing this from a modern win 8.1 app and let you know how it went.

Additionally, I'll see if I can make the "Add RAML reference" available for Shared Projects, even though I'm not sure I'll have much time for such thing.

**Comment by dmalanij** [comment]
Just created pull request #22 with my changes.

**Comment by dmalanij** [comment]
Thanks Pedro!!! Yesterday I was just checking on version 0.9.4 and 0.9.6 of the RAML.Api.Core and was nicely surprised it was already supporting the Universal Apps. 
Hope the changes in the pull request were helpful.

**Comment by woodp** [comment]
Diego, sorry, forget to thank you for the pull request !
Of course they were helpful, thanks again !
