### ISSUE TITLE
README references missing image file in docimages directory

### ISSUE THREAD

**Issue by jawn** [mulesoft-labs/raml-dotnet-tools#200]
The readme 
https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/README.asciidoc

references this missing image file:
> image::./docimages/XmlCommentsDocumentation.png[align="center"]

**Comment by woodp** [comment]
Thank you.
New docs can be found at https://github.com/mulesoft-labs/raml-dotnet-tools/wiki
