### ISSUE TITLE
RAML 0.8 Response Content property not generated

### ISSUE THREAD

**Issue by guillaume-fr** [mulesoft-labs/raml-dotnet-tools#206]
Generate client for attached groups.raml using vs extension
The response isn't properly generated (no Content property). Yet the type is generated and I'm able to do a ReadAsAsync on the RawContent.

[v1-api.zip](https://github.com/mulesoft-labs/raml-dotnet-tools/files/2599140/v1-api.zip)

**Comment by woodp** [comment]
@guillaume-fr cannot reproduce. A GroupsGetResponse type is generated, this type has the Content property, which is the typed Response.
Otherwise reopen with more info.
