### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by jawn** [mulesoft-labs/raml-dotnet-tools#207]
Visual Studio 2019 has been released.

This [article](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) describes how to modify the .vsixmanifest to add Visual Studio 2019 support.

I don't know if that's enough to make it work, let me know if I should try this with a PR.

**Comment by woodp** [comment]
Thanks for the feedback @jawn

**Comment by jawn** [comment]
Hello @woodp 

Any news whether this is on the roadmap?

**Comment by woodp** [comment]
VS 2019 supported in the latest beta version
