### ISSUE TITLE
Saving RAML no longer updates enum members

### ISSUE THREAD

**Issue by jawn** [mulesoft-labs/raml-dotnet-tools#208]
Given a Visual Studio 2017 project with a .RAML that generates Web Api.
A while ago this used to work but now:

✔️ Adding an api creates a new class 
❌ Adding an enum member for an existing request parameter type checks out the file from sourcce control, but does not add the member. Still something is happening since Visual Studio warns me that the extensions worked for 10 seconds or so.
👁 The ActivityLog does not show anything special.

Before I start troubleshooting, any hints to what could cause this?
* Same results after reinstalling the add-in.
* Same results when running Visual Studio as admin.
* I see the web project has been upgraded from JSON.NET 6.0.4 to 10.0.3
* An older version lists a Raml.Parser.1.0.7 in the packages folder, the current doesn't. I don't know whether this is used.
* ~~I installed Visual Studio 2019~~. Update: Tested on a machine with and without Visual Studio 2019 installed in addition to the Visual Studio 2017 used to test this.

Curious if there is some caching or so going on?

**Comment by woodp** [comment]
fixed in the latest release
