### ISSUE TITLE
URL does not url encode parameters

### ISSUE THREAD

**Issue by iambigred** [mulesoft-labs/raml-dotnet-tools#210]
Hi,

I'm encountering an issue whereby parameters containing non-url safe characters (e.g. &) are not not encoded when the url is constructed.  See screenshot below.  This causes the request to fail.  I am using v2.1.2, the latest available release on the VS marketplace.

![image](https://user-images.githubusercontent.com/6648996/65673036-f89c4e00-e041-11e9-9eaf-cd329ebe0bdf.png)

**Comment by woodp** [comment]
this has been fixed in the latest release
