### ISSUE TITLE
Unable to import RAML file from local machine

### ISSUE THREAD

**Issue by cryo75** [mulesoft-labs/raml-dotnet-tools#240]
Trying to import a simple RAML file from the local machine, having this content:

`

	#%RAML 1.0
	title: REST Services API
	version: v1
	protocols: [ HTTPS ]
	baseUri: http://194.168.1.2:8083/api/v1
	mediaType: application/json
	types:
	  MyEnum:
		enum: [Value1, Value2, Value3, Value4]
	  VersionResponse:
		type: object
		properties:
		  result: integer

	/test/get_version:
	  post:
		description: Invoke method get_version
		responses:
		  200:
			body:
			  application/json:
				type: VersionResponse
		  500:
		  501:
		  503:
`

But all that happens is an endless progressbar and nothing gets imported. Is this an issue with the current version of the plugin?

**Comment by woodp** [comment]
fixed on the latest release
