### ISSUE TITLE
Two nodes with the same name cause code overwrite

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#25]
If you have a RAML file that has two nodes with the same name, such as:

```YAML
   /workers:
      /{id}:
        put:
          body:
            application/json:
              schema: WorkerProfile        
        get:
          responses:
            200:
              body:
                application/json:
                  schema: WorkerProfile            
    
```
And

```YAML
  /addresses:
      /{id}:
        get:
          description: Retrieve the address with the specified ID
          responses:
            200:
              body:
                application/json:
                  schema: Address
        put:
          body:
            application/json:
              schema: Address 

```

When the C# classes are created, only one Idputrequest model object is created (for workers). The put method for addresses uses the Idputrequest model defined by the WorkerProfile schema and not the one defined by the Address schema. Changing {id} to {workerid} and {addressid} does cause the two classes to properly generate, each defined by the respective schema.

**Comment by dmalanij** [comment]
I've seen something similar but couldn't test it properly. Clearly, when nesting the resources you loose the context for the creation of the classes (that are taking only the name of the parameter in the current level but no considering the ancestors).

If you only need to define the get and put by id and nothing else for both resources maybe you can work around this by defining the resources as /addresses/{id} and /workers/{id}. Not very clean but can work. You can even apply this if you want to have /addresses and /workers on their own, but in that case you'll end up with two different controllers for each resource root...

**Comment by woodp** [comment]
Haven't had time to test it with the current released version but I could not reproduce this with the develop version. Will get back to you on this as soon as I can.

**Comment by tb-wwparker** [comment]
I used a slight different workaround. I changed addresses/{id} to addresses/{addressid} and workers/{id} to workers/{workerid} and it generated the proper code. I'm consuming someone else's RAML file, so restructuring it is not an option (a rename might be possible).

**Comment by woodp** [comment]
I can't reproduce this. 
Use latest release and if it fails again then please provide a complete RAML sample.
