### ISSUE TITLE
Generate protected methods

### ISSUE THREAD

**Issue by vincpa** [mulesoft-labs/raml-dotnet-tools#26]
Just an idea.

Can the code generation for WebAPI methods call to out to a protected method ? That was I can inherit controllers and override the protected methods. That way when the controllers are blown away during code generation I won't lose my changes.

So instead of

    /// <summary>
    /// Get the info of a movie
    /// </summary>
    /// <param name="id"></param>
    /// <returns>IdGetOKResponseContent</returns>
    public IHttpActionResult GetById([FromUri] string id)
    {
        // TODO: implement GetById - route: movies/{id}
        // var result = new IdGetOKResponseContent();
        // return Ok(result);
        return Ok();
    }

It would be

    /// <summary>
    /// Get the info of a movie
    /// </summary>
    /// <param name="id"></param>
    /// <returns>IdGetOKResponseContent</returns>
    public IHttpActionResult GetById([FromUri] string id)
    {
        // TODO: implement GetById - route: movies/{id}
        // var result = new IdGetOKResponseContent();
        // return Ok(result);
        return GetByIdImpl(id);
    }
    protected IHttpActionResult GetByIdImpl(string id) {
         return Ok(); // Do other stuff here
    }

I can then have the generated class somewhere else and have my concrete implementations override methods.

**Comment by woodp** [comment]
Actually it already works similar to what you say.

"Concrete" controllers (the ones under the "controllers" folder) only get generated once. All the code you place on those will **not** get modified at all when regenerating. Only the interface and the "base" controllers (nested within the RAML file, on the "contracts" folder) are regenerated.

Let me know if you have any more doubts about this.
