### ISSUE TITLE
The requested resource does not support http method 'PUT'.

### ISSUE THREAD

**Issue by PaulJoW** [mulesoft-labs/raml-dotnet-tools#28]
Hi All.

I've imported a RAML file as outlined into VS 2013.
However, only GET requests work. All other request get the "The requested resource does not support http method ... " message.
I have tried so many of the suggested solutions on the Web. Most of these talk about WebDav issues. I do not have webdav installed. I have tried adding protocols to web config, to IIS, routing options ...  [HttpPut] [Route("{id}")] etc etc. Have installed a new copy of VS2013, tried running on the freshly installed IIS and Express.

I have run out of options. Has anyone else experienced this or have any other options for me to try please?

Thanks,
Paul

**Comment by woodp** [comment]
Hi @PaulJoW this doesn't seem to be related to the tool.
Anyway if you paste your RAML I can take a look.

**Comment by PaulJoW** [comment]
Thanks @woodp 
Here is my RAML
#%RAML 0.8
title: Contacts
version: "1.0.0"
baseUri: "https://apitest.name.ac.nz:443/ucapi"
schemas: 
    - 
        "contact": '{"type":"object","description":"UC Staff Contact details","title":"contact","properties":{"type":{"type":"string","required":true,"title":"type"},"id":{"type":"string","required":true,"title":"id"},"displayName":{"type":"string","required":false,"title":"displayName"},"givenName":{"type":"string","required":false,"title":"givenName"},"surname":{"type":"string","required":false,"title":"surname"},"email":{"type":"string","required":false,"title":"email"},"telephoneNumber":{"type":"string","required":false,"title":"telephoneNumber"},"officeName":{"type":"string","required":false,"title":"officeName"}}}'
        "contacts": '{"type":"object","description":"The representation that contacts data is returned","title":"contacts","properties":{"data":{"type":"array","required":false,"title":"data","items":{"type":"object","$ref":"#/schemas/contact"},"uniqueItems":false},"status":{"type":"string","required":false,"title":"status"}}}'
        "error": '{"type":"object","title":"error","properties":{"status":{"type":"string","required":false,"title":"status"},"message":{"type":"string","required":false,"title":"message"}}}'
/contacts:
  displayName: "Contacts"
  get: 
        queryParameters: 
            "givenNameQuery": 
                displayName: "givenNameQuery"
                description: "Filter on given name"
                type: string
                required: false
                repeat: false
            "surnameQuery": 
                displayName: "surnameQuery"
                description: "Filter on surname"
                type: string
                required: false
                repeat: false
        responses: 
            "200": 
                description: "Successful contacts search"
                body: 
                    "application/json": 
                        schema: "contacts"
                        example: '{"status":"success","data":[ { "id": "abc123", "type" : "contacts", "displayName": "Paul Test", "givenName": "Paul Joseph", "surname": "Test", "email": "paul.test@test.ac.nz", "telephoneNumber": "93158", "officeName": "Test DF05" }, { "id": "abc124", "type" : "contacts", "displayName": "Jamie Test", "givenName": "Jamie Test", "surname": "Test", "email": "jamie.test@test.ac.nz", "telephoneNumber": "93261" }]}'
  /{id}:
    displayName: "Contact"
    get:
        description: "A contact by Id"
        responses: 
            "200": 
                body: 
                    "application/json": 
                        schema: "contacts"
                        example: '{"status":"success","data":[{ "id": "abc123", "type" : "contacts", "displayName": "Paul Test", "givenName": "Paul Test", "surname": "Test", "email": "paul.Test@Test.ac.nz", "telephoneNumber": "93158", "officeName": "Test DF05" }]}'
            "404": 
                body: 
                    "application/json":
                        schema: "error"
                        example: '{"message":"error","status":"Resource Not Found"}'
    put:
      description: "Update a contact" 
      body:
        "application/json":
          example: '{ "id": "abc123", "type" : "contacts", "displayName": "Paul Test", "givenName": "Paul Test","surname":"Test","email":"paul.test@test.ac.nz", "telephoneNumber": "93158", "officeName": "Test DF05" }'
      responses:
            "200": 
                body: 
                    "application/json": 
                        schema: "contacts"
                        example: '{"status":"success","data":[{ "id": "abc123", "type" : "contacts", "displayName": "Paul Test", "givenName": "Paul Joseph","surname":"Test","email":"paul.test@test.ac.nz", "telephoneNumber": "93158", "officeName": "Test DF05" }]}'
            "404": 
                body: 
                    "application/json":
                        schema: "error"
                        example: '{"message":"error","status":"Resource Not Found"}'

**Comment by woodp** [comment]
Ok, so other than 2 get methods there is only a put method. 
So no other method will work.
The nesting of the RAML didn't come thru but it seems the PUT is under the /{id} resource so you need to be sure to add the id to the route. A PUT to /contacts/1/ should work.

**Comment by PaulJoW** [comment]
Thanks again @woodp 
Yes, you are correct. Unfortunately the PUT does not work and I get the not supported message. I have tried changing and adding other methods and re-importing too ... but only GET seems to work.

I'm pretty sure the RAML is good. I have used it with other tools to generate tests and documentation and they interpret it.

**Comment by woodp** [comment]
I tried with your RAML. The tool is generating the method this way: 
*put(string content, [FromUri] string id)*

Since *content* is a primitive type ASP.NET expects it to come in the URL, so a PUT to */contacts/1?content=xyz* will work, but if you don't specify the content param in the query it will issue the message you are getting.

This is a bug in the tool, will include fix in next release.

In the meantime, specifying the schema for the PUT method in the RAML will solve your problem.

**Comment by PaulJoW** [comment]
Hi.
I have just got back to trying to resolve this and I am still having issues. I have re written my RAML to just include a PUT and also tried the RAML from http://raml.org/

Can anyone post a simple PUT method  (Complete RAML definition) which they can confirm is imported as described in the instructions and that works with the default generated code please?

Would be very much appreciated and will hopefully help me determine where my issue is. I would really like to be able to use and recommend the use of this tool as a default starting place for our team.

I am running as pre-reqs but with Visual Studio 2013 update 4.
Thank you.

Cheers,
Paul

**Comment by PaulJoW** [comment]
I have tried new/other RAML files and get exactly the same issue. Then, when removing all but a PUT Route I get another continuously repeatable issue.

For example I have replicated this all the time using other users RAML e.g.
   /workers:
      /{workersid}:
        put:
          body:
            application/json:
              schema: WorkerProfile        
        get:
          responses:
            200:
              body:
                application/json:
                  schema: WorkerProfile      

If I just include the PUT section I get
{
  "Message": "No HTTP resource was found that matches the request URI 'http://localhost:61639/workers/123'.",
  "MessageDetail": "No action was found on the controller 'Workers' that matches the request."
}

Leaving both as above i can call the GET method but still see my other error
 "The requested resource does not support http method PUT "

I have tried many different routing options. Renamed id.
I would expect the above example would work 'out of the box'?

What am I missing? I have a freshly installed VS2013 sp4. Is this the problem?
Is there a working solution/example I can download which has the RAML imported.
If I install the RAML Tools via VS2013 >> Extensions and Updates am I getting the latest version?

Thanks in advance for any guidance.
Cheers,
Paul

**Comment by PaulJoW** [comment]
Hi @woodp 

Sorry I didn't see your response. I will give this ago tomorrow and hopefully my additional 2 comments above are useful and not too much spam!

Thanks.

**Comment by PaulJoW** [comment]
Just a quick note that I am including the schema in the RAML.
Does this mean the new version will allow the JSON from the Request Body?

**Comment by woodp** [comment]
Fix will be included in next release.

@PaulJoW if you specify schema in the request of the PUT in your RAML it will work. 
Please see the Movies WebAPI sample included in the sources: https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/samples/MoviesWebApi2Sample
There you have a complete RAML spec (included a PUT) and the generated code.
