### ISSUE TITLE
Non-required JSON elements are not nullable

### ISSUE THREAD

**Issue by wolfgang42** [mulesoft-labs/raml-dotnet-tools#29]
The following JSON schema:
```json
{
	"type": "object",
	"properties": {
		"DEFAULT": {
			"type": "number",
			"required": true
		},
		"optional": {
			"type": "number"
		}
	},
	"additionalProperties": false,
	"required": true
}
```
generates this C# code:
```C#
public partial class Offers
{
	public decimal DEFAULT { get; set; }
	public decimal optional{ get; set; }
}
```

The problem here being that the 'optional' property is not in fact optional. Everything works as expected if you change it to a `Nullable<decimal>` like so:
```C#
	public decimal? optional{ get; set; }
```
However you have to re-apply this fix every time, since it gets overwritten when you update the RAML contract.

**Comment by woodp** [comment]
Fix will be included in next release. 
In the meantime you can use type: ["number", "null"]
