### ISSUE TITLE
Querystring Parameter Name Creation Broken

### ISSUE THREAD

**Issue by carltstein** [mulesoft-labs/raml-dotnet-tools#3]
e.g. This code is produced:

   if(getbankaccountsquery.Customerid != null)
                    url += "&getbankaccountsquery.Customerid=" + getbankaccountsquery.Customerid;

Created from the following RAML extract:
  /bank-accounts:
    type: collection
      get:
        queryParameters:
            customer-id:
              type: string

Issues:
  * Queryname prefix is incorrectly being including in the actual querystring ("&getbankaccountsquery.")
  * Hyphens are being stripped from the queryParameter name ("customer-id" -> "Customerid")
  * Capitalisation is being applied to the first character of the querystring name which breaks any function call

**Comment by carltstein** [comment]
Solutions for Queryname prefix issue is:
  File: GeneratedModel.t4
  Change Line 87 to: url += "&<#= property.Name #>=" + <#= method.Query.Name.ToLower() #>.<#= property.Name #>;

**Comment by woodp** [comment]
Thanks carltstein

**Comment by woodp** [comment]
tag: Issue 3
