### ISSUE TITLE
Unable to custom path of generated model classes

### ISSUE THREAD

**Issue by laellyo** [mulesoft-labs/raml-dotnet-tools#30]
Hello,

First of all, thanks for you VS tool, it very useful to be able to manage RAML in .NET to create Web API. :)
We tried your tool, it works well but we have one constraints that it doesn't meet for now.
We would like to be able to choose the output of the generated model classes. We check the code, the path is currently hardcoded in the class RamlScaffoldService.

Concretely, in our case, we would like to generate all model classes in the "Models" folder, with the following pattern <./Models/xxxx.generated.cs> to indicate to developers that these classes has not to be modified directly.

Do you know if you plan to improve your current .NET tool to allow this customization in the future?

Thanks in advance!
David

**Comment by woodp** [comment]
This feature will be included in next release
