### ISSUE TITLE
JsonPatch schema causes an Object not set to an instance error on Import

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#31]
I have a RAML file that defines several schemas, including the one that causes the erro:

   JasonPatch: !jsonPatch.schema

Where jsonPatch.schema is a JSON Patch schema (see http://jsonpatch.com/)

	"title": "JSON schema for JSONPatch files",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "array",
	"items": {
		"$ref": "#/definitions/operation"
	},
	"definitions": {
		"operation": {
			"type": "object",
			"required": [ "op", "path" ],
			"allOf": [ { "$ref": "#/definitions/path" } ],
			"oneOf": [
				{
					"required": [ "value" ],
					"properties": {
						"op": {
							"description": "The operation to perform.",
							"type": "string",
							"enum": [ "add", "replace", "test" ]
						},
						"value": {
							"description": "The value to add, replace or test."
						}
					}
				},
				{
					"properties": {
						"op": {
							"description": "The operation to perform.",
							"type": "string",
							"enum": [ "remove" ]
						}
					}
				},
				{
					"required": [ "from" ],
					"properties": {
						"op": {
							"description": "The operation to perform.",
							"type": "string",
							"enum": [ "move", "copy" ]
						},
						"from": {
							"description": "A JSON Pointer path pointing to the locatoin to move/copy from.",
							"type": "string"
						}
					}
				}
			]
		},
		"path": {
			"properties": {
				"path": {
					"description": "A JSON Pointer path.",
					"type": "string"
				}
			}
		}
	}
}

When I use the Add RAML menu option in Visual Studio 2013, it returns an Object not set to an instance error during the import. 

From what the developer that wrote the RAML said, they have had issues with using this RAML due to the fact that the type is "array" (all other schemas in the project use a type of object). Does the tool support a schema type of array?

**Comment by woodp** [comment]
The tool supports array schema types. 

I detected and fixed the null reference error, it will be included in next release. 
But the tool does not fully support json schema v4 and in particular it does not support the json patch schema.

**Comment by woodp** [comment]
Null reference error fixed.
Note that jsonpatch is not supported so the tool will not generate an object for this
