### ISSUE TITLE
Error when importing RAML file

### ISSUE THREAD

**Issue by Grauenwolf** [mulesoft-labs/raml-dotnet-tools#35]
I am getting this error when importing a RAML file:

    ---------------------------

    ---------------------------
    One or more errors occurred. - Error parsing: while reading file
    error: while scanning a double-quoted scalar
      in "c:/XXX/Contracts/includes/leagues.raml", line 6, column 34
    found unknown escape character l
      in "c:/XXX/Contracts/includes/leagues.raml", line 6, column 44
      in "C:\XXX\Contracts\api.v1.raml", line 31, column 11
    ---------------------------
    OK   
    ---------------------------

The line in question is: 
    collection-example: !include "includes\leagues.collection.example.json"

The original line (pre-import) was 
    collection-example: !include "leagues.collection.example.json"

**Comment by woodp** [comment]
I was able to reproduce the error. 
Removing the double quotes will solve the error:
      collection-example: !include includes\leagues.collection.example.json

**Comment by Grauenwolf** [comment]
I'm new to RAML. Are those quotes considered to be non-standard or is this a bug in the tool?

**Comment by woodp** [comment]
The parser works well with double quoted includes. This error is not on the parser but on the tools

**Comment by tb-wwparker** [comment]
In our testing, what we found the error to be was not the quotes, but the use of a sub-directory.

If you try to use _!include_ **includes\**_leagues.collection.example.json_, then things don't work
If you use _!include leagues.collection.example.json_, then the includes work. 

This appears to be a bug in both the Mulesoft Anypoint studio and the RAML tools for .Net.

**Comment by woodp** [comment]
@tb-wwparker we now support using relative includes, let me know if you have any issues

**Comment by Grauenwolf** [comment]
Thank you, I look forward to trying this out.
