### ISSUE TITLE
Object reference not set to instance of an object (Visual Studio 2015/RAML Tools for .NET 1.2.0)

### ISSUE THREAD

**Issue by olssochk** [mulesoft-labs/raml-dotnet-tools#36]
When trying to regenerate/update code from a RAML file the following message appears:

![image](https://cloud.githubusercontent.com/assets/13046720/10459112/598b97de-71ce-11e5-8ad0-4671ef4d162a.png)

The problem is this JSON schema file and the "required" keyword. I know this because if I remove the "required" keyword it works fine:
![image](https://cloud.githubusercontent.com/assets/13046720/10459236/fad448fc-71ce-11e5-9b74-4fd66046f83d.png)

A similar JSON schema file passes through the parser without problems:
![image](https://cloud.githubusercontent.com/assets/13046720/10459219/e3b1fbd8-71ce-11e5-920c-dbb3596633e7.png)

The difference here is that the object is not contained in an array.

**Comment by woodp** [comment]
@olssochk json shcema v4 support is partial, and required as an array is one of the non supported features.
But that gave me some info to work with, hopefully enough to add support for it. 
Thanks for the feedback.

**Comment by tb-wwparker** [comment]
This happens to me on a regular basis . I am using Arrays, but not the required tag.
I find that if I run the Update RAML function a second time, then it usually works the second time.
I think there might be a problem with how the system fails, deletes the .cs file and TFS throws an error. The second time, the file doesn't exist, so the error is not thrown.

**Comment by woodp** [comment]
required as an array is now supported 
null reference fixed
