### ISSUE TITLE
Generated code for PATCH Http requests doesn't compile

### ISSUE THREAD

**Issue by danielhall** [mulesoft-labs/raml-dotnet-tools#39]
In the generated code for patch requests, the following line does not compile.

```
var req = new HttpRequestMessage(HttpMethod.Patch, url);
```
```
Error CS0117 'HttpMethod' does not contain a definition for 'Patch'
```

I've been trying to figure whether I'm referencing the wrong libraries, however the official Microsoft documentation also suggests that the class HttpMethod does not support a property called Patch.
https://msdn.microsoft.com/en-us/library/system.net.http.httpmethod

Are you able to reproduce this? I have referenced System.Net.Http version 4.0.0.0.

**Comment by woodp** [comment]
@danielhall what version of the tool are you using ?

This issue was solved and the generated code now looks like this:

```
var req = new HttpRequestMessage(new HttpMethod("Patch"), url);
```
