### ISSUE TITLE
Incorrect capitalisation of schema properties

### ISSUE THREAD

**Issue by carltstein** [mulesoft-labs/raml-dotnet-tools#4]
The following auto generated properties are incorrectly capitalized leading to failed calls:

Generated code extract: 
  public partial class BankAccountsPutRequestContent 
    {
        /// <summary>
        /// The id of the bank account
        /// </summary>
        public string BankAccountId { get; set; }
        /// <summary>
        /// Name of the bank
        /// </summary>
        public string BankName { get; set; }
        /// <summary>
        /// ISO country code for the bank's country
        /// </summary>

From RAML:
  - put-bankAccount: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "bankAccountId" : {"type" : "string","description": "The id of the bank account"},
          "bankName" : {"type" : "string","description": "Name of the bank"},

**Comment by woodp** [comment]
will be included in next release

**Comment by woodp** [comment]
fixed in v 1.0.0
