### ISSUE TITLE
Timeline for RAML 1.0 support?

### ISSUE THREAD

**Issue by cuctc** [mulesoft-labs/raml-dotnet-tools#40]
I realize that the 1.0 spec just dropped today, and I'm excited to get going with this. It looks like there have been some great improvements. I've been kicking the tires with 0.8 but am ready to get moving with some production code and will need to decide which version to proceed in. I've had some issues with 0.8 and am hoping by moving to 1.0 they'll get left behind. But if it will be a long lead time in revising this tool to support 1.0, I'll need to make a decision on whether to continue with 0.8 or some other alternative.

Thanks
Tom

**Comment by magic-cure** [comment]
Hi Tom - support for RAML 1.0 is under development with a mid Q1 2016 target.

Regards
Derek.

**Comment by pgatilov** [comment]
Hi, is mid Q1 2016 still the goal?

Thanks.

**Comment by cuctc** [comment]
Do you have an updated timeline for completion? 

Thanks

**Comment by neilhosey** [comment]
Hi,

I was curious if 1.0 was supported yet?  Great tools by the way!!

Neil

**Comment by jackreyneke** [comment]
Hi guys,
Are you still working on RAML 1.0 support?
Cheers

**Comment by pgatilov** [comment]
Looking at the activity at https://github.com/mulesoft-labs/raml-dotnet-tools/commits/raml1edge, seems like they are working on support. Hope now that RAML 1 is GA, we can have a timeline in a couple of weeks.

**Comment by sichvoge** [comment]
Hi guys, I have great news. We plan to do a release early next week. ;)

**Comment by indiealexh** [comment]
Request closing of this issue due to bbc22e4 fulfilling this request.

**Comment by JohnMcAvinue** [comment]
Is 1.0 supported now so? It shouldn't be closed unless the answer is yes.

**Comment by JogoShugh** [comment]
Weill there be a new extension in the gallery for it? I saw the 2.0 source code release, but not in the gallery yet. Thanks!

**Comment by sichvoge** [comment]
Let me investigate why you don't see it in the gallery yet.

**Comment by magic-cure** [comment]
Because it hasn't been published yet... now waiting on me to upload. Hopefully today.
