### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by jhallam3** [mulesoft-labs/raml-dotnet-tools#41]
Hi when importing a url I get the attached problem. 

![screen shot 2015-11-06 at 11 47 01](https://cloud.githubusercontent.com/assets/5174328/10996357/422bbef0-847c-11e5-8149-eca9f3fe81f3.png)

**Comment by woodp** [comment]
Can you check if you have an included resource that itself has includes ? 
If that's the case it is a known issue.

**Comment by jhallam3** [comment]
Hi not sure where to look.

**Comment by woodp** [comment]
Your main RAML file must be including "traits.raml" and that file is trying to include "common_400.example" file.  The tools fails to resolve the path in this cases. Have not found a fix for this issue yet.

For the tools the example file does not add value so as a workaround you can remove the include of the example file (common_400.example)

Files are downloaded to the TEMP folder, so you can grab them from there and do the necessary modifications

**Comment by woodp** [comment]
Includes inside includes now work with new js parser
