### ISSUE TITLE
Generate meta data failed with validations

### ISSUE THREAD

**Issue by ToXinE** [mulesoft-labs/raml-dotnet-tools#46]
When generating metadata from WebApi2 the raml definition is missing some properties : 

My object is :

        public class DossierSignatureModel
        {
            public string SignId { get; set; }
            public IEnumerable<KeyValuePair<int, string>> Users { get; set; }
            public bool IsCancelable { get; set; } 
            public string Statut { get; set; }
            public DateTime SignDate { get; set; }
            public int FileId { get; set; }
        }

and it generates the following RAML def : 

      - IEnumerable1: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "type": "array",
            "items": 
            {
              "type": "object",
              "id": "DossierSignatureModel",
              "properties": 
              {
                "SignId": { "type": "string"},,
                "IsCancelable": { "type": "boolean"},
                "Statut": { "type": "string"},
                "SignDate": { "type": "string"},
                "FileId": { "type": "integer"}
              }
            }
          }

(Look at the double comma following SignId...)

Causing the following validation error :

{"context":"while validating body","context_mark":null,"message":"schema is not valid JSON error: 'Unknown Character ',', expecting a string for key statement.'","problem_mark":{"name":"/Raml/Raw","line":405,"column":0,"buffer": ....

Does RAML dot net tool support collection inside object ?

**Comment by woodp** [comment]
A type inside a collection is supported, what is not supported is KeyValuePair<>

**Comment by woodp** [comment]
Could you please specify how would you expect the resulting JSON Schema to be ?

Would adding "additionalProperties": true work for you ?

**Comment by ToXinE** [comment]
I'm not aware of an "additionalProperties" to set. Where can i set this property ? 
When generating metadata for WebApi with the extension RAML Tool for .NET, I right click on my web project and select "Enable RAML metadata output for this project" and it creates the controller RAMLController.cs and some other files.

I'm not sure of what i expect : 
Something like 
```
    - IEnumerable1: |
     {
    	"$schema": "http://json-schema.org/draft-03/schema",
    	"type": "array",
    	"items": 
    	{
    	  "type": "object",
    	  "id": "DossierSignatureModel",
    	  "properties": 
    	  {
    		"SignId": { "type": "string"},
    		"Users":
    		{ 
    		  "type": "array",
    		  "items": {
    			"type": "object",
    			"properties": 
    			{
    				"Key": { "type": "int"},
    				"Value" : { "type": "string"}
    			},
    		  }
    		},
    		"IsCancelable": { "type": "boolean"},
    		"Statut": { "type": "string"},
    		"SignDate": { "type": "string"},
    		"FileId": { "type": "integer"}
    	  }
    	}
    }
```

**Comment by woodp** [comment]
I added support for KeyValuePair, it will be included in next release.

additionalProperties is a JSON Schema keyword. See https://github.com/json-schema/json-schema/wiki/Additionalproperties
