### ISSUE TITLE
Responses not shown when RAML metadata enabled

### ISSUE THREAD

**Issue by PabloInNz** [mulesoft-labs/raml-dotnet-tools#47]
I have been using the example RAML file from the RAML 200 tutorial. When viewing the API documentation created by running the "Enable RAML metadata output", the "Responses" tab never seems to show anything. I would expect it to show the examples. Am I mis-understanding something ?
![ramldoc](https://cloud.githubusercontent.com/assets/16217026/11793473/b04033b4-a310-11e5-86ba-07d5fce56595.png)

**Comment by woodp** [comment]
The scaffold does not take into account the examples. There is no standard structure to put the examples in a WebApi app. Some sort of special documentation has been considered but not implemented.

Similarly when extracting the RAML from a WebApi there is no standard structure / place to extract the examples from.

**Comment by PabloInNz** [comment]
Ah, OK, thanks for the reply
