### ISSUE TITLE
Query Parameter doesn't work with all webservers

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#49]
If you have a RAML file that defines an end point with query parameters, the auto-generated code constructs a URL of the form http://domain/endpoint?&parameter1=data&parameter2=data, which works just fine when the API end point is running on an IIS server. However, when the endpoint is a Mulesoft API gateway, you get a NullReferenceException from the WebServer.

Could you fix the auto-generated code to suppress the first &, so that the URL looks like  http://domain/endpoint?parameter1=data&parameter2=data and doesn't cause problems for Java based WebServers that don't seem to parse URLs of the ?& correctly?

**Comment by woodp** [comment]
fix will be included in next release
