### ISSUE TITLE
Bool query params rejected

### ISSUE THREAD

**Issue by carltstein** [mulesoft-labs/raml-dotnet-tools#5]
Capital 'T' in 'True' submitted by proxy via query parameter is rejected by the service with the following error. 

org.mule.module.apikit.MappingExceptionListener
Message               : Invalid value 'True' for query parameter FxApplyConvention. Value must be one of [true, false]
Code                  : MULE_ERROR--2

Suggested fix: simply force boolean parameters to lower case.

Thanks!

(By the way, thanks for fixing the other issues I submitted)

**Comment by woodp** [comment]
thank you for the feedback!

fixed in version 1.1.0
