### ISSUE TITLE
Response headers not copied to headers structure

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#50]
If you have a RAML that looks like this:
```YAML
  post:
    description: "Create a new job site by customer. (JobSite.CreateJobSite)"
    body:
      application/json:
        schema: JobSiteModel
    responses:
      201:
        headers:
          Location:
            description: "The relative url of the created resource" 
```

When you call the end point, it returns a relative URI of the form /jobsites/12345 in the header named Location. The generated code has the following lines:
```c#
var headers = new Models.PostApiJobsitesCreatedResponseHeader();
headers.SetProperties(response.Headers);
```
But the Location header does not get copied to the headers data structure. Looking at the data structure, the data browsers points out that most of the methods throw an illegal operation error on relative URIs. There does appear to be a work around, which is to copy the value from the RawHeaders structure like this:
```c#
var rawLocation = response.RawHeaders.Location.ToString();
```

**Comment by menduz** [comment]
Same here!

**Comment by woodp** [comment]
fix will be included in next release
