### ISSUE TITLE
Wrong Newtonsoft Required attribute

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-dotnet-tools#51]
When I use "Add RAML Contract" command the generated model classes contain what I think it would be the Newtonsoft attribute Required. For example:
```
namespace RamlDotNetCompiler.Api.Models
{
    public partial class DoSomethingPutRequestContent
    {
        [Required]
        [JsonProperty("id")]
        public int Id { get; set; }
    }
}
```

"[Required]" is wrong and should be expressed like:
```
[JsonProperty("id", Required = Required.Always)]
```

**Comment by woodp** [comment]
@giacgbj I did a simple test and using [Required] turns the model invalid, which is what I would expect while "Required.Always" does not. 
You would have to manually deserialize the model to json to get a validation exception.
What would then be the benefit ?

**Comment by giacgbj** [comment]
I think we are talking about two different things: I'm just saying that the code **automatically** generated by "raml-dotnet-tools" doesn't compile because "[Required]" is not a valid attribute of the **automatically** installed Newtonsoft's Json.NET library.

**Comment by woodp** [comment]
Oh, ok, then what type of project and version of visual studio are you using and which is the error ?

Note that the scaffolding when adding a contract is for WebApi.

[Required] is part of System.ComponentModel.DataAnnotations which is included in a WebApi project.

**Comment by giacgbj** [comment]
@woodp, thanks for the clarification. 
I thought that was a (wrong) Newtonsoft annotation because of the lack of the attribute Required inside the annotation itself. If it's the desired behavior, you can close the ticket.
