### ISSUE TITLE
Generated code does not have a using for the Models namespace

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#52]
I built a new project with the most recent RAML.Api.Code library.
I added a RAML to project.
When I built the project, it gave me the error message
Error	7	The type or namespace name 'ApiQuoteClientLogPostRequestContent' could not be found (are you missing a using directive or an assembly reference?)	C:\src\QA\Automation\QuoteEstimator\QuoteEstimatorTests\QuoteEstimatorTests\API References\QuoteEstimator\QuoteEstimator.cs	1100	59	QuoteEstimatorTests

When I add "using QuoteEstimatorTests.QuoteEstimator.Models;" to the top of the auto-generated file, it builds just fine.

I have not had to do that for any of my other projects (and all of the other models were found in this project).

What might cause this issue?

**Comment by woodp** [comment]
fix will be included in next release
