### ISSUE TITLE
Issues importing RAML definition for 3 level deep objects

### ISSUE THREAD

**Issue by danielhall** [mulesoft-labs/raml-dotnet-tools#54]
I am having issues whenever I try to import RAML containing request objects nested 3 levels deep.

I get the following error when using the Visual Studio tool (v 1.3.0) to import the RAML.
![image](https://cloud.githubusercontent.com/assets/2905855/12322371/918eae0c-baab-11e5-86fe-e8e1f4a7f142.png)

I have a RAML definition file which references the following JSON file (containing the schema for a request).

```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Create",
	"type": "object",
	"required": ["PropertyOne"],
	"properties": {
		"PropertyOne": {
			"type": "string"
		},
		"Details": {
			"title": "Details",
			"type": "object",
			"required": ["PropertyTwo"],
			"properties": {
				"PropertyTwo": {
					"type": "string"
				},
				"Address": {
					"title": "Address",
					"type": "object",
					"required": ["Line1"],
					"properties": {
						"Line1": {
							"type": "string"
						},
						"Line2": {
							"type": "string"
						},
						"Line3": {
							"type": "string"
						},
						"Line4": {
							"type": "string"
						}
					}
				}
			}
		}
	}
}
```

Now, I know that this error is caused by objects that are three-levels deep, because if I take out the Address object, and add it to the root-level object, the definition imports without any issues.

This issue also occurs if the 3rd level object is nested inside an array.

Is this a known issue or do you know of any work-around which will allow me to nest these objects?

**Comment by woodp** [comment]
I was able to reproduce this error.

As a momentary work-around you can convert it into a version 3 JSON schema (simply remove the required as array and place it in each property)

**Comment by woodp** [comment]
fix will be included in next release

**Comment by danielhall** [comment]
Thanks @woodp. 
I tried out the work-around you suggested and that works well.
