### ISSUE TITLE
Enable RAML metadata output

### ISSUE THREAD

**Issue by benoitbac** [mulesoft-labs/raml-dotnet-tools#55]
Hi, 
I would like to test your tool but I got an error when I'm trying to "Enable RAML metadata output" on my projet.
The error is : 
"Error when trying to enable RAML metadata output. Updating 'Microsoft.AspNet.WebApi.ore 5.2.3' to 'Microsoft.AspNet.WebApi.ore 5.1.2' failed. ..."
Is it not compatible with higher than 5.1.2 version ? 
Tks in advance.

**Comment by woodp** [comment]
The tool is compatible with 5.2.3 version.

This is a nuget issue. Nuget fails to update WebApi.Core from a nuget package.

We explicitly changed the dependency to 5.1.2 to overcome this nuget issue....it should not try to update to 5..2.3. Could you provide more context on how it this happening, which specific visual studio version, which type of project, etc.

As a workaround, just manually upgrade to 5.2.3 on your project and then try again.
