### ISSUE TITLE
section for definition.example is not rendered for raml api console

### ISSUE THREAD

**Issue by gitsnail** [mulesoft-labs/raml-dotnet-tools#56]
Hi,

I'm testing out using the movies.raml example.
After enabling RAML metadata output, I navigated to the apiConsole http://localhost/raml. 
Although the example is defined for /movies.get.responses.200.body, the example section is not rendered, only the schema is.

As seen in the screenshot I got,  is empty.
![apiconsolemovies](https://cloud.githubusercontent.com/assets/4794553/12462829/50e7e552-bf8e-11e5-8f9e-37bb59f2b5b3.png)

Thanks,
Ruishi

**Comment by woodp** [comment]
There is no standard way of declaring an example in WebAPI, so when you generate a WebAPI from a RAML the example sections won't get anywhere. The same applies for RAML Metada output, there is no standard place to get the example from when extracting a RAML from a WebAPI.
