### ISSUE TITLE
additionalProperties not supported?

### ISSUE THREAD

**Issue by carltstein** [mulesoft-labs/raml-dotnet-tools#6]
In the following example the AdditionalInfo object is not supported in the generated proxy class (aside from schema validation).

{
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "Property1" : {"type" : "integer"}, 
          "Property2" : {"type" : "string"},
          "AdditionalInfo": {
            "type": "object", 
            "additionalProperties": {"type": "string", "description": "Additional key-value pairs"}
          }
        }    
      }

**Comment by schmkr** [comment]
Does this plugin support draft-04?

**Comment by woodp** [comment]
schmkr support for draft 4 is partial 
this schema for example is supported http://json-schema.org/example2.html 
but required property as an array is not

**Comment by woodp** [comment]
Actually, required property as an array is supported. My mistake, sorry.

Anyway v4 support is partial.

**Comment by woodp** [comment]
Support for additionalProperties will be included in next release
