### ISSUE TITLE
Unable to host multiple versions of the API within the same application

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#62]
Let's assume you have your application running the first version (**v1**) of the API. After sometime you realize the API needs changes so you work on a new RAML defintion getting the **v2**. Now, if you want to have both APIs created through RAML.Net tools coexisting you are forced to create a different application and keep them as separate things to ensure isolation by different base URIs at an IIS level.

This has several implications specially regarding maintenance and support (you end up with two versions of source code) and also the ability to reuse base functionality. Not to mention the difficulty if you host multiple APIs on the same web application and those APIs can evolve independently.

It would be really good to have some mechanism to allow this kind of "multiple APIs per web application scenarios". 

As for the particular case for multiple versions, I've worked on some changes to allow including the API version as a prefix for the controllers routes so for a raml like this:
```
#%RAML 0.8
title: Movies
version: v1
baseUri: http://movies.com/api
mediaType: application/json
protocols: [HTTP]
/movies:
  get:
```

You can easily chose the *MoviesController* gets routed as 

- movies (current implementation)
- **v1/**movies (prefixing the *version* attribute from the RAML)

You can find it on the dmalanij/raml-dotnet-tools@a5907f4bcc41bca048696b88d6cf51db33c1f87f commit. Happy to create a pull request if you find it valuable.

**Comment by woodp** [comment]
Diego, thank you very much for your input.
Let me analyse this thoroughly and get back to you.

**Comment by csalzsieder** [comment]
@woodp is there any plans to add this feature?

**Comment by jackson5280** [comment]
@woodp same question as above, can this be added sometime soon in the future? It would be very useful!

**Comment by crmorgan** [comment]
@woodp, Has there been any progress on including this or some kind of version support?  My company is currently evaluating the MuleSoft ESB product and RAML .NET tool and versioning our controllers is a must for us.  Being able to include the resource version number in the generated controller names as either a prefix (V1MoviesController, V2MoviesController) or as a suffix (MoviesV1Controller, MoviesV2Controller) would be a great feature.

**Comment by davidkeaveny** [comment]
TBH, we much prefer running different versions of our API in virtual directories under our site root. So https://myapi.com becomes the developer portal, and the API versions are deployed into /v1.0, /v1.1 virtual directories underneath,

Maintenance of older versions is then carried out in the way that maintenance of any other software project is done - through using the features of your source control, so we will have a maintenance branch for v1.0 of the API; and if no changes are required to be made to that version, then it never need be touched, and it runs isolated in its own w3wp process. Our automated deployments take care of creating new virtual directories when deploying a new major.minor release. 

To put all versions of an API in one branch, whether you use namespaces, class naming, or whatever, sounds like a real headache when you are up to version 10.2 of your API, and every single version gets built together.

**Comment by woodp** [comment]
Sorry, been busy with the RAML 1 release.
Will process this now.

**Comment by woodp** [comment]
@dmalanij if you only change the routing you still have to deal with controller names colliding, or how do you plan to handle that ?

**Comment by dmalanij** [comment]
@woodp you're right, haven't precisely thought around that but certainly could apply a strategy (like setting a different namespace or a prefix itself)

**Comment by woodp** [comment]
@dmalanij OK, please send the pull request if you can, thank you !

**Comment by woodp** [comment]
This feature will be included in next release. 
I agree with @davidkeaveny, so this will be totally optional and default behaviour won't include it.

**Comment by crmorgan** [comment]
Using a virtual directory per version is a good way to support URI based versioning for sure but for us is not an option at the moment.   We are using a custom controller selector that will return the appropriate controller class based on the version supplied in the request which can be done in the URI, mime type, or the header.  There are trade offs for both approaches and having the ability to support both in this tool is great.

**Comment by woodp** [comment]
thanks for the input @crmorgan 
I hope it will cover your needs. 
Feedback is welcome so once released please send any further comments.
