### ISSUE TITLE
DotNet RAML parser cannot parse nested JSON schemas of request bodies

### ISSUE THREAD

**Issue by flavio1110** [mulesoft-labs/raml-dotnet-tools#64]
When I use a nested object like this is request body the tool is not able to create the classes properly. And the expected parameter in Action becomes string.

Examples:

addredd.json
=====================
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Address",
  "type": "object",
  "properties": {
    "addressLine1": {
      "required": "true",
      "type": "string"
    },
    "zipCode": {
      "required": "true",
      "type": "string"
    }
  }
}

=====================

order.json
=====================
{
  "$schema": "http://json-schema.org/schema#",
  "type" : "object",
  "properties" :{     
      "id" : {
        "required": "true",
        "type" : "string"
      },
    **_  "billAdress" : {
        "required": "true",
        "type" : "object",
        "$ref" : "address"
      }_**
    }
  }

=====================

service.raml
=====================
#%RAML 0.8
title: Service XPTO
baseUri: https://to.be.defined:8080/{version}
mediaType: application/json
protocols: [ HTTP, HTTPS ]
version: v1.0.0

schemas:
  - address: !include address.json
  - order: !include order.json

/auth:
  post:
    body:
      application/json:
        schema: order
    responses:
      200:
        body:
          application/json:
            schema: order
=====================

ps.: It isn't the real code.

**Comment by flavio1110** [comment]
Related:
https://github.com/mulesoft-labs/raml-dotnet-tools/issues/13

**Comment by woodp** [comment]
This sample works fine.
You might be affected by Issue #59 which has been fixed but not released (coming soon)
