### ISSUE TITLE
"Url does not exist in current context" for /raml when added to pure WebApi project

### ISSUE THREAD

**Issue by stephenfuqua** [mulesoft-labs/raml-dotnet-tools#65]
I have a pure WebAPI project, created in Visual Studio 2015. I added the RAML .NET tools via Extension Manager, and used existing metadata to create the RAML. Initially, attempting to view `/raml` generated a Razor compilation error in the RAML view: "_The name 'Url' does not exist in the current context_". I was able to resolve this by adding `@inherits System.Web.Mvc.WebViewPage` into `Index.cshtml`. 

Although I've resolved the issue locally, I want to put this tip out for others who might run into the same situation. There is probably a `web.config` setting that is missing, but I did not look into that since I already had a solution.

**Comment by JogoShugh** [comment]
Any luck with this? We are seeing similar problems.

**Comment by woodp** [comment]
fix will be included in next release
