### ISSUE TITLE
Question: how to produce a DateTime data-type?

### ISSUE THREAD

**Issue by danielhall** [mulesoft-labs/raml-dotnet-tools#67]
Is it possible to define a property in the JSON schema that would produce a DateTime data-type in the C# generated code?

The only way I know how to define a date in JSON is as follows:

`    "InstructionDate": {
      "type": "string",
      "format": "date-time"
    }`

But the above produces a string in the generated code.

**Comment by woodp** [comment]
It will be possible when we release the Tools for RAML 1, using the [RAML 1 Types which include the date data type](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#date)

**Comment by danielhall** [comment]
Ok thanks @woodp
