### ISSUE TITLE
Where is the VSIX file?

### ISSUE THREAD

**Issue by Ofer-Gal** [mulesoft-labs/raml-dotnet-tools#7]
Can't find the Tool file.
Also after cloning the entire solution the tools project did not load with error
	MuleSoft.RAML.Tools\MuleSoft.RAML.Tools.csproj: The application which this project type is based on was not found

I have VS2013 update 4

**Comment by woodp** [comment]
The vsix is available on the visual studio gallery. There several ways to get the extension:

- From Visual Studio, select "Tools" menu, then "Extensions and Updates", search "Online" for RAML and click on install.

- Or you can download it from
https://visualstudiogallery.msdn.microsoft.com/cadcb820-762c-4514-9817-884b7558aaa9

- Or you can download the sources and build the solution, you need the Visual Studio SDK that you can download from here: https://www.microsoft.com/en-us/download/details.aspx?id=40758

**Comment by Ofer-Gal** [comment]
Thank you much
