### ISSUE TITLE
Version 1.4.1 - file not found errors for all include files

### ISSUE THREAD

**Issue by DavidEHerbst** [mulesoft-labs/raml-dotnet-tools#70]
After upgrading to version 1.4.1, I’m seeing file not found errors (see appended screen capture) for all the include files when saving RAML files.  This even happens with RAML files fresh from our Git repository which previously saved without error and that I have not altered.  As a workaround I have to globally replace “include/” with “../include/” to save and generate the server side code.

Unfortunately the workaround doesn’t seem to work for our client applications that reference the same RAML to generate the client side code.

![raml include save error](https://cloud.githubusercontent.com/assets/19712045/15750020/57b5db2a-28aa-11e6-964d-84e59a211722.png)

**Comment by rstraszewski** [comment]
We have exactly the same problem.

**Comment by danielhall** [comment]
I've got the same issue. 
Unfortunately I haven't had any luck with the workaround above.

**Comment by woodp** [comment]
We are working in a new release, coming out very soon. 
Please use the previous vsix or wait for the new release.

**Comment by DavidEHerbst** [comment]
Where can we find/download the vsix for the previous version?

**Comment by lvillap** [comment]
Same happening here. It seems as a base folder it takes the name of the file, not the folder containing it. How could I download the previous vsix?

**Comment by danielhall** [comment]
Has anybody found the previous vsix yet?

**Comment by woodp** [comment]
The new vsix is out https://visualstudiogallery.msdn.microsoft.com/cadcb820-762c-4514-9817-884b7558aaa9
