### ISSUE TITLE
date types like date-only and time-only do not work

### ISSUE THREAD

**Issue by urbanssn** [mulesoft-labs/raml-dotnet-tools#71]
Thanks for the awesome tool. Creating a model from my raml 1.0 file currently however results in errors, that the types date-only, time-only and datetime are unknown. However, the file is valid (and works for example with the api-console after #276 in the api console was fixed).
Messages are of the kind "Error: property timestamp refers to unknown type datetime..."

**Comment by woodp** [comment]
These are not supported by the RAML js parser we are using.
New version does include support for these so we will be updating the js parser and releasing a new version of the tools

**Comment by woodp** [comment]
fixed in the last release
