### ISSUE TITLE
Add RAML is missing for Asp.Net Core Web Application

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#72]
Hi,

After updating to latest Asp.Net Core (RC2), the option "Add RAML Contract..." is no longer available, I updated to the latest version of RAML Tools "2.0.0" but still not working, I also tried a regular Asp.Net Web Application and it's working fine, so it seems the issue is only with "Asp.Net Core Web Application" projects.

Please advise how this can be fixed
Thanks

**Comment by woodp** [comment]
"Add RAML Contract..." is not supported for .net core yet.

**Comment by vanthome** [comment]
I want to use RAML with a .NET Core project developed in VS Code (on Linux/ OSX). Will you support this stack, is there any roadmap?

**Comment by woodp** [comment]
Asp.net core scaffolding ("Add RAML Contract...") will be supported in next release (from Visual Studio).

@vanthome the CLI tools are aimed to use with VS Code (or in a CI scenario), but full .net core support is not yet possible since we depend on edge.js which is not .net core compatible (yet).

**Comment by ThomasGrausgruber** [comment]
In Visual Studio 2015 Update 4? Do you have an estimated release date for this version?
