### ISSUE TITLE
Problem with generating controllers with new version of .NET tools

### ISSUE THREAD

**Issue by rstraszewski** [mulesoft-labs/raml-dotnet-tools#74]
Hi, after update to 2.0.0 version, we have problem with action paramaters, now generated code looks like this:
`public virtual HttpResponseMessage PostBase([FromBody] string content)`

Instead of something like this:
`public HttpResponseMessage Post(DocumentsPostRequestContent documentsPostRequestContent)`

All of our actions have now `string content` as parameter, instead of model generated from json schema. In version 1.4.0 everything worked ok.

Anyone had this problem?

**Comment by woodp** [comment]
Could you please provide a RAML sample that reproduces this behaviour ?
