### ISSUE TITLE
How to switch the HTTP client between content types

### ISSUE THREAD

**Issue by robertbird** [mulesoft-labs/raml-dotnet-tools#75]
Hi there, 

Thanks so much for building and maintaining this project it is really useful.

I have a RAML API hosted in Mule and a .net client built with these tools calling the API. The API supports both application/json and application/xml content types. 

I am trying to build a test harness which can switch between the content types and show the request/response data. I have the following code:

     ```
            // Add Accept header
            var httpHeaders = new HttpHeaders();
            httpHeaders.Add("Accept", "application/xml");
            httpHeaders.Add("Content-Type", "application/xml");
            requestObj.RawHeaders = httpHeaders;

            // Set the XML formatter
            requestObj.Formatter =  new XmlMediaTypeFormatter();

            // call the API
            var apiResponse = _apiClient.MyMethod.Post(requestObj);
    ```

Unfortunately this does not work...Is this the correct way to do it? Am I headed in the right direction? Are there any examples? does anyone else have this working?

It is very close, but the problem I am having is that the XML generated has the wrong root XML element name. It gets the same name as the class which is very long and includes things taken from the path etc. 

I would really appreciate any help that anyone can offer!

Thanks again for the great tool - it has saved us a lot of time.

**Comment by woodp** [comment]
Hi, you shouldn't do anything special in your client code. The RAML itself should specify that you are handling XML. The code looks just the same as it you would be handling json:

```
           var client = new OrdersXmlClient("https://someurl/");
            var response = await client.Orders.Get("1");
            var order = response.Content;

            var resp = await client.Orders.Post(order);

```
There's a sample [here](https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/samples/OrdersClientSample)

If that doesn't work for you please send your RAML.
