### ISSUE TITLE
"Package restore failed" when trying to import RAML definition

### ISSUE THREAD

**Issue by scottflute** [mulesoft-labs/raml-dotnet-tools#78]
I'm trying to import https://raw.githubusercontent.com/spotify/web-api/master/specifications/raml/api.raml into my C# project using VS 2015 Update 3.
I'm able to preview the import, but when I actually progress to the next step, I get an error message:
"Error: Package restore failed.  Rolling back package changes for xxxxx"

Is this a problem with my nuget configuration?  As far as I can tell, it's set to restore packages so I don't know :-/

**Comment by woodp** [comment]
I cannot reproduce this in VS 2015 update 3 (nor update 2).
What nuget package is failing ?
Are you importing this in a brand new project ? what type of project ? Otherwise, what nuget packages do you have already installed ?
