### ISSUE TITLE
Can not generate ResponseContent if a trait is involved.

### ISSUE THREAD

**Issue by NoevilMe** [mulesoft-labs/raml-dotnet-tools#79]
I defined traits.

![image](https://cloud.githubusercontent.com/assets/2884278/16736263/d45089ea-47be-11e6-8043-e3c8fca506d5.png)

And want to generate ASP.NET Web API code for this resource.
![image](https://cloud.githubusercontent.com/assets/2884278/16736374/428812c0-47bf-11e6-9b12-3c0f3cde408a.png)

But **the corresponding ResponseContent class couldn't be generated**.
If I delete the line I marked, a CompaniesGetOKResponseContent class will exist.

**Comment by woodp** [comment]
Fix will be included in next release.
