### ISSUE TITLE
Use $schema to determine schema version

### ISSUE THREAD

**Issue by schmkr** [mulesoft-labs/raml-dotnet-tools#8]
I noticed that the `JsonSchemaParser.cs` uses a quite remarkable way to determine whether the schema should be parsed against v3 or v4 of the json schema spec, [by checking for the existence of the `oneOf`keyword](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/a47e611605af4600964cc08c589227d0d08b4d66/Raml.Tools/JsonSchemaParser.cs#L26).
However, you can still write a valid v4 schema without the oneOf keyword. 

Wouldn't it be much more reliable to check for the existence of the `$schema` keyword and if it exists, use that to validate the schema against? In cases where there is no `$schema` keyword available, you could fallback to the trial and error approach like it is now.

**Comment by woodp** [comment]
schmkr, thank you for the feedback

The code does **not** rely on the "oneOf" keyword  to determine wether is a v3 or v4 json schema. It relies on JSON.NET.
We found later that some specific schemas were wrongly detected and thus added the "oneOf" exception. But in the absence of the "oneOf" keyword [it uses JSON.NET to determine](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/Raml.Tools/JsonSchemaParser.cs#L75).

Sadly I've seen too many *$schema* incorrectly tagged to rely on it.

Thanks again for the feedback.
