### ISSUE TITLE
Cannot import seemingly valid project

### ISSUE THREAD

**Issue by p-kaczynski** [mulesoft-labs/raml-dotnet-tools#82]
Using Import RAML into brand new WebAPI2 project.
Trying to import api.raml from attached RAML project.
[RAML.zip](https://github.com/mulesoft-labs/raml-dotnet-tools/files/397367/RAML.zip)

I get following error:
<img width="398" alt="ramlimportissue1" src="https://cloud.githubusercontent.com/assets/5558396/17334443/3352179a-58ce-11e6-9d77-5974448c3e2b.png">

The RAML seems valid to Atom/api-workbench. Unfortunately there doesn't seem to be enough information for me to investigate it myself.

**Comment by p-kaczynski** [comment]
Also, I have noticed, that this seems to be an error that happens inside the raml-js-parser-2. From what I can see, bundled version is 0.2.6, while current is 0.2.30. I have tried parsing my project with both versions, and 0.2.6 fails, while 0.2.30 seems to work fine. Would you be able to bump the bundled parser version?

**Comment by p-kaczynski** [comment]
I have tested the changes from referenced commit locally, it does indeed work for me as well now.

**Comment by woodp** [comment]
great, thanks for the feedback
