### ISSUE TITLE
Controllers using Route instead of RoutePrefix in WEB API 2

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#83]
In the new 2.0.2 version, the contollers generated when importing a RAMLcontract  to a WebAPI solution are getting a Route attribute instead of RoutePrefix, which causes to conflict with the routes for the actions themselves.

This is caused by a change in the MuleSoft.RAML.Tools/Templates/RAMLWebApi2Scaffolder/ApiControllerBase.t4 in commit 4645da244616d7c4d081b54044ba4c58f05bbeea 

@woodp not sure if this was intentional or just a change done by mimicing what's been done for the ASPNet5 templates

**Comment by woodp** [comment]
Thanks for spotting that Diego, will fix it ASAP.

**Comment by dmalanij** [comment]
You're welcome, @woodp .
I've also noticed a very trivial thing on the ASP.Net 5 templates, just reported the issue #84 for that. It was part of the process of identifying the problem with WebAPI that made me review the others as well.
Hope it helps!

**Comment by gitsnail** [comment]
Replacing "RoutePrefix" to "Route" also breaks my api routing.
I edited file ApiControllerBase.t4 locally as a temp fix for the issue.

It would be great to fix it from the source asap though.

Best!
