### ISSUE TITLE
Unable to cast object of type 'System.Dynamic.ExpandoObject' to type 'System.String'

### ISSUE THREAD

**Issue by salpon** [mulesoft-labs/raml-dotnet-tools#85]
I tried importing jukebox-api.raml from raml.org raml-tutorial-200 (https://github.com/raml-org/raml-tutorial-200.git) in VS2015 Community. I can see that it imported  jukebox-api.raml into Contracts folder and the remaining files in Contracts/include folder. But then it gives me the below error:

Unable to cast object of type 'System.Dynamic.ExpandoObject' to type 'System.String'

**Comment by woodp** [comment]
fix will be included in next release

**Comment by dmalanij** [comment]
+1
I was about to report this last week, found it while using parameterized traits. @woodp, if you need an example, let me know
