### ISSUE TITLE
Customizing to work with MvcCodeRouting project?

### ISSUE THREAD

**Issue by JogoShugh** [mulesoft-labs/raml-dotnet-tools#86]
Hello,

I love what RAML Tools does to generate my models and method signatures. But, I'd like to rely on the convention-based namespace-aware routing provided by the MvcCodeRouting library which makes routes for you based on class names and namespaces. (Details: https://github.com/maxtoroq/MvcCodeRouting/blob/master/docs/Controllers-and-Namespaces.md)

For example, I have a contract with `ProjectRoles/ByProject` and `ProjectRoles/ByMember` in it. When RAML tools builds this, it produces classes with names:

`ProjectRolesByProjectController`
and
`ProjectRolesByMemberController`

and thus routes with `ProjectRoles/ProjectRolesByProject` etc.

With MvcCodeRouting, if I have the following classes:

``` csharp
namespace Web.ProjectRoles {
  public class ByMemberController : ApiController {
    public IHttpActionResult Get() {}.
}
```

``` csharp
namespace Web.ProjectRoles {
  public class ByProjectController : ApiController {
    public IHttpActionResult Get() {}.
  }
}
```

Then, MvcCodeRouting will automatically produces routes of:

`ProjectRoles/ByMember` and `ProjectRoles/ByProject`

This way, I do not need to rely upon any `Route()` attributes, the `HttpGet` attribute, nor do I particularly need the partial classes or the interfaces.
## Question

I've tried modifying the T4 templates, but I can't seem to get what I want. It just crashes on me when I attempt to access "namespace" or attempt to bring in the WebApiGeneratorModel parameter.

I see the `$(namespace)` is only a post-processing replacement.

The closest I was able to come is not reliable, because sometimes it shows T4TemporaryAssembly, but here's what I was trying.

Oddly enough the code that reads:

``` csharp
var nsFullName = System.Reflection.Assembly.GetExecutingAssembly().FullName;
var nsPrefix = nsFullName.Substring(nsFullName.LastIndexOf(".") + 1);
```

Well, it did actually work once or twice, but then it just started returning T4TemporaryAssembly.

The current workaround of hard-coding the `var nsPrefix = "ProjectRoles"` is definitely not ideal. Being able to change the output path/filename would be ideal too.

I'm willing to contribute a pull-request to help with this, if someone can give me some pointers on getting started. Thanks!

``` csharp
<#
// title: Controller Implementation
// hash: 8fcfd9754864b06ccdad423b06ef0a7a
// version: 3.0
#>
<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="$(binDir)Raml.Tools.dll" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="Raml.Tools" #>
<#@ import namespace="Raml.Tools.WebApiGenerator" #>
<#@ import namespace="System.Linq" #>
<#@ parameter name="controllerObject" type="Raml.Tools.WebApiGenerator.ControllerObject" #>
<#@ parameter name="hasModels" type="System.Boolean" #>
<#@ parameter name="useAsyncMethods" type="System.Boolean" #>
<#@ parameter name="apiVersion" type="System.String" #>
<#@ output extension=".cs" #>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
<# if(hasModels){ #>
using $(namespace).Models;
<# } #>
<#
//var nsFullName = System.Reflection.Assembly.GetExecutingAssembly().FullName;
//var nsPrefix = nsFullName.Substring(nsFullName.LastIndexOf(".") + 1);
var nsPrefix = "ProjectRoles";
var name = controllerObject.Name.Substring(nsPrefix.Length);
#>
namespace $(namespace)
{
<# if(System.String.IsNullOrWhiteSpace(apiVersion)) { #>
    public partial class <#= name #>Controller : ApiController
<# } else { #>
    public partial class <#= apiVersion #><#= name #>Controller : ApiController
<# } #>
    {

<#
        foreach (var method in controllerObject.Methods)
        {
#>
<#= method.XmlComment ?? string.Empty #>
<# if(useAsyncMethods) { #>
        public async Task<IHttpActionResult> <#= method.Name #>(<#= method.ParametersString #>)
<# } else { #>
        public IHttpActionResult <#= method.Name #>(<#= method.ParametersString #>)
<# } #>
        {
            // TODO: implement <#= method.Name #> - route: <#= controllerObject.PrefixUri + "/" + method.Url #>
<#
    if (method.ReturnType != null && method.ReturnType != "string")
    {
#>
            // var result = new <#= method.ReturnType #>();
            // return Ok(result);
<#
    }
#>
            return Ok();
        }

<#

        }
#>
    }
}
```

**Comment by woodp** [comment]
Hi, 
about the namespace, not sure why are you trying to change the namespace in the template, you can change it directly in the UI. 

about the name of the controllers, they can't be changed using the template, you would need to change the code, check the [GetUniqueObjectName method](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/e79eaa5aaf72a6c1407124f7135f4fea042a6c17/Raml.Tools/GeneratorServiceBase.cs#L387)  on GeneratorServiceBase class

**Comment by JogoShugh** [comment]
Thanks @woodp I'll look into that. About the namespace, I wasn't trying to change the namespace, but trying to change the controller name based on knowing that the controller name was getting created with the namespace as the prefix.
