### ISSUE TITLE
Date parameter type incorrectly converted from RAML to C#

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#88]
Let's have a RAML definition like this:

```
/articles/{date}:
  uriParameters:
    date:
      description: Date you want the articles from
      type: date
  get:
    description: Retrieves the articles for a given date
    responses:
      200:
```

When importing that into your C# project the following gets generated:
```
public virtual IHttpActionResult GetBase([FromUri] object date)
```

Instead of
```
public virtual IHttpActionResult GetBase([FromUri] DateTime date)
```

And in runtime the parameter is just getting it's string value.

**Comment by woodp** [comment]
That's because date does not exist in the RAML spec, you need to use datetime, date-only or some the other possible date types.

You can check the [date types in the spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#date).

**Comment by dmalanij** [comment]
I might be mistaken but, isn't RAML spec 0.8 specifically saying **date** is the correct way to describe the type of a parameter that represents a "date/time stamps"?  Check this: https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md#type

**Comment by woodp** [comment]
Your are right, forgot to check 0.8 spec!
