### ISSUE TITLE
Allow to customize how parameter types are translated from RAML to C#

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#89]
This is actually an enhancement. Currently the tools are generating the types of the controllers methods parameters internally, based on the type taken from the RAML
As far as I can tell the following are the mappings:
* string -> string
* date -> object (see #88) 
* integer -> int
* number -> decimal

That's quite good but due to the limitations in the RAML 0.8 specification of parameter types might not be accurate, we faced this when trying to expose an API that we have ids defined as longs, no matter what type we choose in RAML, we face the problem that the code representation is not accurate:
* integer: when we get an ID beyond the Int32.MaxValue the API will stop working as the formater will start yielding overflows
* string: the API won't be correctly expressing what type is expected and we still have to convert / parse the value
* number: similar to the string case, even though at least we know is numeric

We are working with **number** for now, but this made me think it would be good to have some level of manipulation on how the types are translated. Default mappings are (or should be) OK in most of the cases, but sometimes you might need to tweak it. Integer is probably the most representative case as it really means a wide range of types (short, int, long), and is up to your implementation which really suits it.

**Comment by woodp** [comment]
@dmalanij  as always, thanks for the feedback.
We'll consider this, in the meantime I changed to use long as a default instead of int. 
That would be enough to cover the scenario you mentioned.
Will be available in next release.

**Comment by dmalanij** [comment]
You're welcome. There's a small team working with me so probably that's also why I concentrate so much feedback :)

I believe using long is good enough, as it's the largest available for representing integer numbers. Maybe customizing is too much, I can think on very weird scenarios for such a thing but probably not worth it. 

Thanks!

**Comment by woodp** [comment]
This was addressed by using long as a default instead of int

**Comment by woodp** [comment]
Example to obtain a .NET long type in the generated code:

RAML 1:

    types:
        longprop:
            type: number
            format: long

RAML 0.8:

    {
        "longprop": { "type": "number", "format": "long" }
    }


More info [here](https://github.com/mulesoft-labs/raml-dotnet-tools#fine-tuning-generated-net-primitive-types)
