### ISSUE TITLE
How do I set samples for JSON, XML and otherwise.

### ISSUE THREAD

**Issue by ssuing8825** [mulesoft-labs/raml-dotnet-tools#9]
How do I set a schema for XML?

Are these features on the roadmap?

**Comment by woodp** [comment]
XML schemas are not supported yet but on the roadmap, we hope to have them included in the next release.
JSON schema are already supported.

**Comment by ssuing8825** [comment]
Thanks for the quick reply! What about examples/samples?

**Comment by woodp** [comment]
You have examples of the use of the RAML toools in the samples folder https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/samples
Those are based on the Movies API RAML: https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/samples/MoviesClientSample/movies.raml

You have several API examples here https://anypoint.mulesoft.com/exchange/#!/?types=API

Also, there is a sample used by the RAML tutorial here: https://github.com/raml-org/raml-tutorial-200.git

Hope that covers your needs
