### ISSUE TITLE
Failure to generate server contract after building RAMLGen from source

### ISSUE THREAD

**Issue by samuelhewitt** [mulesoft-labs/raml-dotnet-tools#90]
On a Windows 7 box with .NET 4.5.1 installed.
I pulled master e79eaa5a and built the project (I had to swap 1.0.2.0 in for 1.0.3.0 of the Raml.Parser, since 1.0.3.0 is not publicly available).

When running the command line tool, failure with message:
runtime error CS0234: Compiling transformation: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)

I was able to fix this by modifying the CustomCmdLineHost.cs file:
1) StandardAssemblyReferences 
                    typeof(System.Uri).Assembly.Location,
                    typeof(System.Linq.Enumerable).Assembly.Location
2) StandardImports
                    "System",
                    "System.Linq"

**Comment by woodp** [comment]
Will check that.
Do you need a previous version of the code for some reason ?
Can you instead use the [latest release](https://github.com/mulesoft-labs/raml-dotnet-tools/releases/tag/v2.0.3) ?

**Comment by samuelhewitt** [comment]
@woodp Sorry, should have clarified. I verified the commit I pulled from master is the same as latest release (v2.0.3) before I pulled it.

**Comment by woodp** [comment]
Now this version and it's dependencies are released so you should have no problems building from source.
