### ISSUE TITLE
When will release 2.0.3 become available?

### ISSUE THREAD

**Issue by adam-resdiary** [mulesoft-labs/raml-dotnet-tools#91]
Sorry if I'm missing something here, it's just that I notice there's a 2.0.3 on the Github releases page, but the Visual Studio extension gallery seems to still be sitting on 2.0.2. Any idea when the latest version will be available?

It's just a bit confusing at the moment, because I think the documentation in the README currently references the latest version.

**Comment by woodp** [comment]
It is released now

**Comment by adam-resdiary** [comment]
Great - thanks a lot.
