### ISSUE TITLE
optional properties

### ISSUE THREAD

**Issue by hmts82** [mulesoft-labs/raml-dotnet-tools#93]
When using optional properties in RAML for example:
`Mail:
    type: object
    properties:
      Id?: integer`

The generated model doesn't create a nullable property?

the generated code is:
`public int Id { get; set; }`

**Comment by hmts82** [comment]
I have compiled and installed the latest version but the problem continues happening.
I have tried also with required set to false but no joy.

thanks

**Comment by woodp** [comment]
this has not been released
also, the key change for this is in the [parser](https://github.com/raml-org/raml-dotnet-parser-2)

if you don't want to wait for the release you need to compile and generate the nuget package from the develop branch and use that in this project (also using develop branch)

**Comment by hmts82** [comment]
I have noticed that just now.
I have tested and it looks ok.

thanks

**Comment by hmts82** [comment]
I have changed to
` if (!prop.Required && propertyType != "string" && prop.Type != "file" )`

When i was receiving a file the generated code was:
`public byte[]? Id { get; set; }`

**Comment by hmts82** [comment]
the required properties where generating nullable values also.

made the folowing change to solve the problem:
`if (!prop.Scalar.Required && propertyType != "string" && prop.Type != "file" )`

**Comment by woodp** [comment]
Would you like to make a pull request with that change ?
