### ISSUE TITLE
integer types generating long type after last release

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#94]
Hi,

After getting the latest tool release 2.0.3 all integer types are now being generated as C# type long instead of int, this is breaking all our code as in business logic and repository layer we are using int type, so we are getting build errors.

I can see that this change has been implemented in response to issue #89 and I can see in this issue that there was a workaround there by using number type which will generate C# type decimal, while the applied change to resolve that issue is a breaking change for us and anyone who's using int C# type in business logic layers

Can you please revert back this change so it generates C# type int, or at least add a support for format as described in Raml 1.0 definition so we can have control over what C# type will be generated?

Quote from Raml 1.0 definition "The format of the value. The value MUST be one of the following: int32, int64, int, long, float, double, int16, int8"

Thanks

**Comment by woodp** [comment]
Thanks for the feedback. 
Using the format property is a good suggestion.

**Comment by amikhaildev** [comment]
Thanks, I noticed you already did some code changes for this, I got the latest from develop branch and built it, it seems to be working fine, there's only one issue I found, it's failing for json schema with string type and date-time format as it tries to retrieve from NumberFormatConversion whenever there's format attribute, without checking the type 
refer to Raml.Tools.JSON.JsonSchemaParser.GetType method line 297
As a temporary solution in my local code I added a check that the format exist in the dictionary
```
            if (!string.IsNullOrWhiteSpace(property.Value.Format) && NumberFormatConversion.ContainsKey(property.Value.Format))
                type = NumberFormatConversion[property.Value.Format];
            else
                type = NetTypeMapper.Map(property.Value.Type);
```

Thanks

**Comment by woodp** [comment]
Thanks for the feedback @amikhaildev 
Will add your changes

**Comment by woodp** [comment]
Example to obtain a .NET long type in the generated code:

RAML 1:

    types:
        longprop:
            type: number
            format: long

RAML 0.8:

    {
        "longprop": { "type": "number", "format": "long" }
    }


More info [here](https://github.com/mulesoft-labs/raml-dotnet-tools#fine-tuning-generated-net-primitive-types)
