### ISSUE TITLE
Source file path missing in .ref file

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#95]
Hi,

Using the latest release with Aps.net core projects, when adding a new Raml Contract or editing the path of an existing Raml Contract in the project, the Source in .ref file become empty, so the option to "Update Raml Contract from source" is not there anymore.

As a workaround I can update the source in .ref file manually

Thanks

**Comment by woodp** [comment]
This change was intentional. We thought that having a hardcoded absolute path was an impediment for sharing code when working in a team.
Any changes to a RAML contract will cause a regeneration of the code when saving so there's no need to use the Update RAML reference command.
