### ISSUE TITLE
RAML import error when schema consists of complex type objects

### ISSUE THREAD

**Issue by se7vanj** [mulesoft-labs/raml-dotnet-tools#96]
Hi, could you please take a look at the error in snapshot, when we have complex type objects (nested/referring one another) we are getting this error, however the same RAML was validated fine in other online interactive tools.
![error](https://cloud.githubusercontent.com/assets/16820267/18419182/4e2e049c-7823-11e6-9de4-a5f6781c81ff.jpg)

**Comment by woodp** [comment]
Could you please provide the RAML that you are having problems with or a sample where the error is reproducible ?
Thanks
