### ISSUE TITLE
Code generation fails while using custom output folders

### ISSUE THREAD

**Issue by Xanderhed** [mulesoft-labs/raml-dotnet-tools#97]
Code gen will fail every time you try to generate code using the tool if you use a custom output folder. It fails with the error "Unable to add 'First_Model.cs'. A file with that name already exists." with First_Model.cs being the first model in the RAML definition.

**Comment by woodp** [comment]
I can't reproduce this. 
Could you please let me know which version of visual studio, update and type of project are you using ?
Also if possible please send the RAML that is causing the error or a sample to reproduce it.
Thanks
